import Mathlib

/-! Auto-generated by theme/scripts/promote_to_statlib.py.
Do not edit manually; rerun the promotion pipeline.
-/

namespace Statlean
namespace AutoPromoted

section SPDGeometry
/-! Auto-promoted declarations for group: `SPDGeometry`. -/

/-
ID: imported.proposition.004.proposition_3
Title: Proposition 3
Kind: proposition

LaTeX statement:
PROPOSITION 3. On the Riemannian manifold  $(\mathcal{L}_{+},\tilde{g})$ , the geodesic starting at  $L\in \mathcal{L}_{+}$  with direction  $X\in T_{L}\mathcal{L}_{+}$  is given by

$$
\tilde {\gamma} _ {L, X} (t) = \left\lfloor L \right\rfloor + t \left\lfloor X \right\rfloor + \mathbb {D} (L) \exp \{t \mathbb {D} (X) \mathbb {D} (L) ^ {- 1} \}.
$$

LaTeX proof hint:
Proof. Clearly,  $\tilde{\gamma}_{L,X}(0) = L$  and  $\tilde{\gamma}_{L,X}'(0) = \lfloor X\rfloor +\mathbb{D}(X) = X$ . Now, we use  $\operatorname{vec}(L)$  to denote the vector in  $\mathbb{R}^{m(m+1)/2}$  such that the first  $m$  elements of  $\operatorname{vec}(L)$  correspond to the diagonal elements of  $L$ . Define the map  $x:\mathcal{L}_+\to \mathbb{R}$  by

$$
x ^ {i} (L) = \left\{ \begin{array}{l l} \log \operatorname {v e c} (L) _ {i} & \text {i f} 1 \leq i \leq m, \\ \operatorname {v e c} (L) _ {i}, & \text {o t h e r w i s e}, \end{array} \right.
$$

where  $x^{i}$  denotes the  $i$ th component of  $x$ . It can be checked that  $(\mathcal{L}_{+},x)$  is a chart for the manifold  $\mathcal{L}_{+}$ . Let  $e_{i}$  be the  $m(m + 1) / 2$  dimensional vector whose  $i$ th element is one and other elements are all zero. For  $1\leq i\leq m$ , we define  $\partial_i = \operatorname {vec}(L)_ie_i$ , and for  $i > m$ , define  $\partial_i = e_i$ . The collection  $\{\partial_1,\dots ,\partial_{m(m + 1) / 2}\}$  is a frame. One can check that  $\tilde{g}_{ij}\coloneqq \tilde{g}_L(\partial_i,\partial_j) = 0$  if  $i\neq j$ , and  $\tilde{g}_{ii} = 1$ . This implies that  $\pa
...
-/
theorem proposition_004_proposition_3
    {LPlus : Type*} [Add LPlus] [SMul Real LPlus]
    (strictLower : LPlus → LPlus)
    (diagPart : LPlus → LPlus)
    (diagInv : LPlus → LPlus)
    (diagMul : LPlus → LPlus → LPlus)
    (diagExp : LPlus → LPlus)
    (tildeGamma : LPlus → LPlus → Real → LPlus)
    (isGeodesic : (Real → LPlus) → Prop)
    (initialVelocity : LPlus → (Real → LPlus) → LPlus)
    (h_formula :
      ∀ L X : LPlus, ∀ t : Real,
        tildeGamma L X t =
          strictLower L + t • strictLower X +
            diagMul (diagPart L)
              (diagExp (diagMul (t • diagPart X) (diagInv L))))
    (h_start : ∀ L X : LPlus, tildeGamma L X 0 = L)
    (h_initialVelocity :
      ∀ L X : LPlus, initialVelocity L (tildeGamma L X) = X)
    (h_geodesic : ∀ L X : LPlus, isGeodesic (tildeGamma L X)) :
    ∀ L X : LPlus,
      tildeGamma L X 0 = L ∧
        initialVelocity L (tildeGamma L X) = X ∧
        isGeodesic (tildeGamma L X) ∧
        (∀ t : Real,
          tildeGamma L X t =
            strictLower L + t • strictLower X +
              diagMul (diagPart L)
                (diagExp (diagMul (t • diagPart X) (diagInv L)))) := by
  intro L X
  refine ⟨h_start L X, h_initialVelocity L X, h_geodesic L X, ?_⟩
  intro t
  exact h_formula L X t

end SPDGeometry

end AutoPromoted
end Statlean
