import Mathlib

/-!
# Assumption (A2) — conditional (2+ν)-moment bound for high-dimensional mediation

This file formalises **Assumption (A2)** from:

> Lin, Y.; Guo, Z.; Sun, B.; Lin, Z. (2025).
> *Testing High-Dimensional Mediation Effect with Arbitrary Exposure–Mediator
> Coefficients.*  arXiv:2310.05539v3 [stat.ME], 27 May 2025. (Page 8.)

The assumption imposes a conditional `(2+ν)`-moment bound on the mediator
error `E_{M,i}` and the outcome error `Z_i`, conditional on the covariate
vector `X_i`:
$$
  \max_{1\le i\le n}\,\max\!\Bigl\{
    \mathbb{E}[\,|E_{M,i}|^{2+\nu} \mid X_i\,],\;
    \mathbb{E}[\,|Z_i|^{2+\nu} \mid X_i\,]
  \Bigr\}
  \;\le\; M_0
$$
for constants `ν > 0` and `M₀ > 0`.

### Remarks
* The paper writes `E_{M,i}^{2+ν}` without absolute value bars; since
  `2+ν` is a *real* number (not an integer) and `E_{M,i}` may be negative,
  the standard interpretation in the high-moment literature is to read it
  as `|E_{M,i}|^{2+ν}`.  We adopt that interpretation here.
* The conditioning σ-algebra is kept abstract as `𝓧 : Fin n → MeasurableSpace Ω`
  (together with the requirement that each `𝓧 i ≤ m₀` be a sub-σ-algebra
  of the ambient measurable structure on `Ω`).  In practice `𝓧 i` is the
  σ-algebra generated by the random vector `X_i : Ω → ℝ^{q+p}`.
* The paper's outer `max_{1≤i≤n}` and inner `max{·,·}` are equivalent to a
  pair of universally-quantified bounds (one for `E_M` and one for `Z`);
  we use the latter presentation as it is more convenient to apply.
-/

open MeasureTheory

noncomputable section

namespace Statlean.Web.jobmocuz5dbpvoy

/-- **Assumption (A2)** of Lin–Guo–Sun–Lin (2025), arXiv:2310.05539v3, page 8.

The conditional `(2+ν)`-moment of the mediator error `E_M i` and of the
outcome error `Z i`, given the covariate σ-algebra `𝓧 i`, is almost-surely
bounded by `M₀`, for every sample index `i ∈ Fin n`.

Fields:

* `nu_pos` — the excess moment order `ν` is strictly positive;
* `M0_pos` — the moment bound `M₀` is strictly positive;
* `sub_sigma` — each covariate σ-algebra `𝓧 i` is a sub-σ-algebra of the
  ambient `m₀` (a prerequisite for `MeasureTheory.condExp` to make sense);
* `moment_EM` — `𝔼[|E_M i|^(2+ν) | 𝓧 i] ≤ M₀` almost everywhere, for every `i`;
* `moment_Z`  — `𝔼[|Z  i|^(2+ν) | 𝓧 i] ≤ M₀` almost everywhere, for every `i`.
-/
structure AssumptionA2
    {Ω : Type*} [m₀ : MeasurableSpace Ω] (μ : Measure Ω)
    {n : ℕ}
    (𝓧 : Fin n → MeasurableSpace Ω)
    (E_M Z : Fin n → Ω → ℝ)
    (ν M₀ : ℝ) : Prop where
  /-- The excess moment order `ν` is strictly positive. -/
  nu_pos : 0 < ν
  /-- The upper moment bound `M₀` is strictly positive. -/
  M0_pos : 0 < M₀
  /-- Each covariate σ-algebra is a sub-σ-algebra of the ambient one. -/
  sub_sigma : ∀ i : Fin n, 𝓧 i ≤ m₀
  /-- Conditional `(2+ν)`-moment bound on the mediator error `E_M i`. -/
  moment_EM :
    ∀ i : Fin n,
      MeasureTheory.condExp (𝓧 i) μ (fun ω => |E_M i ω| ^ (2 + ν))
        ≤ᵐ[μ] fun _ => M₀
  /-- Conditional `(2+ν)`-moment bound on the outcome error `Z i`. -/
  moment_Z :
    ∀ i : Fin n,
      MeasureTheory.condExp (𝓧 i) μ (fun ω => |Z i ω| ^ (2 + ν))
        ≤ᵐ[μ] fun _ => M₀

namespace AssumptionA2

variable
  {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω}
  {n : ℕ} {𝓧 : Fin n → MeasurableSpace Ω}
  {E_M Z : Fin n → Ω → ℝ} {ν M₀ : ℝ}

/-- The paper's original symmetric statement: the *maximum* of the two
conditional moments is bounded by `M₀` almost everywhere, for every
sample index `i`.  This is the explicit `max{·,·} ≤ M₀` form from page 8. -/
theorem max_moment_le
    (hA : AssumptionA2 μ 𝓧 E_M Z ν M₀) (i : Fin n) :
    (fun ω => max
        (MeasureTheory.condExp (𝓧 i) μ (fun ω => |E_M i ω| ^ (2 + ν)) ω)
        (MeasureTheory.condExp (𝓧 i) μ (fun ω => |Z   i ω| ^ (2 + ν)) ω))
      ≤ᵐ[μ] fun _ => M₀ := by
  filter_upwards [hA.moment_EM i, hA.moment_Z i] with ω hEM hZ
  exact max_le hEM hZ

/-- Symmetry in a trivial but useful direction: if `AssumptionA2` holds for
`(E_M, Z)`, then it also holds for `(Z, E_M)` with the same `ν, M₀`.
This records the fact that the assumption is symmetric in its two error
components, as it is in the paper. -/
theorem swap (hA : AssumptionA2 μ 𝓧 E_M Z ν M₀) :
    AssumptionA2 μ 𝓧 Z E_M ν M₀ where
  nu_pos    := hA.nu_pos
  M0_pos    := hA.M0_pos
  sub_sigma := hA.sub_sigma
  moment_EM := hA.moment_Z
  moment_Z  := hA.moment_EM

end AssumptionA2

end Statlean.Web.jobmocuz5dbpvoy
