import Mathlib

/-!
# MeasureInterLeMin

Promoted from prove session: `cli-20260413-measure_inter_le_min-xxot`
Target theorem: `Statlean.EvolveT8.measure_inter_le_min`
Original file: `Statlean/Web/evolve_t8_measurable/Main.lean`
Cost: $0.085, 6 turns, claude-sonnet-4-6

Generated by evolve/applier/lemma.ts on 2026-04-13.
-/

open MeasureTheory

namespace Statlean.MeasureTheory

variable {Ω : Type*} [MeasurableSpace Ω] {μ : _root_.MeasureTheory.Measure Ω}

theorem measure_inter_le_min (A B : Set Ω) (hA : MeasurableSet A) (hB : MeasurableSet B) :
    μ (A ∩ B) ≤ min (μ A) (μ B) :=
  le_min (measure_mono Set.inter_subset_left) (measure_mono Set.inter_subset_right)

end Statlean.MeasureTheory
