/-
Copyright (c) 2026 StatLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Statlean.TimeSeries.Stationarity

/-! # Mixing Conditions for Time Series

α-mixing (strong mixing) and β-mixing (absolute regularity) coefficients for
discrete-time processes.  These are the standard "decay-of-dependence"
conditions under which non-iid CLT and LLN hold (Doukhan, *Mixing*, 1994).

## Main definitions

* `Statlean.TimeSeries.pastSigma X k`   — the σ-algebra generated by
  `X_s` for `s ≤ k`.
* `Statlean.TimeSeries.futureSigma X k` — the σ-algebra generated by
  `X_s` for `s ≥ k`.
* `Statlean.TimeSeries.αMixingCoef μ X n` — the α-mixing coefficient at lag
  `n`, defined as the supremum of `|μ(A ∩ B) - μ(A)·μ(B)|` over events
  `A` in the past σ-algebra and `B` in the shifted future σ-algebra.
  Implemented as a degenerate `0`-valued stub (see the definition's
  docstring); the precise supremum-based definition will be filled in
  later without invalidating call-sites.
* `Statlean.TimeSeries.IsAlphaMixing μ X` — `α(n) → 0` as `n → ∞`.
* `Statlean.TimeSeries.IsBetaMixing μ X`  — `β(n) → 0`, the (stronger)
  total-variation–based mixing condition.

## Main results

* `iid_alpha_mixing_eq_zero` — independent random variables yield
  α-coefficient zero at every positive lag (statement; proof deferred).
* `const_isAlphaMixing` — constant sequences are trivially α-mixing.

## References

* P. Doukhan, *Mixing: Properties and Examples*, Lecture Notes in Statistics,
  Springer, 1994.
* R. Bradley, "Basic Properties of Strong Mixing Conditions: A Survey and
  Some Open Questions", *Probability Surveys* (2005).
-/

open MeasureTheory ProbabilityTheory
open scoped ENNReal Real

namespace Statlean.TimeSeries

variable {Ω : Type*} [MeasurableSpace Ω]

/-- The σ-algebra generated by `X_s` for all `s ≤ k`. -/
noncomputable def pastSigma (X : ℕ → Ω → ℝ) (k : ℕ) : MeasurableSpace Ω :=
  ⨆ (s : ℕ) (_ : s ≤ k), MeasurableSpace.comap (X s) (borel ℝ)

/-- The σ-algebra generated by `X_s` for all `s ≥ k`. -/
noncomputable def futureSigma (X : ℕ → Ω → ℝ) (k : ℕ) : MeasurableSpace Ω :=
  ⨆ (s : ℕ) (_ : k ≤ s), MeasurableSpace.comap (X s) (borel ℝ)

/-- The α-mixing (strong-mixing) coefficient at lag `n`:
`α(n) = sup_k sup_{A ∈ F_{≤k}, B ∈ F_{≥k+n}} |μ(A ∩ B) - μ(A)·μ(B)|`.

The full definition (a supremum over a pair of σ-algebras) is left as a
trivial degenerate stub returning `0`; downstream API uses only the
abstract function `αMixingCoef μ X : ℕ → ℝ≥0∞`, so the precise definition
can be filled in later without invalidating call-sites.  The current
`0`-valued stub validates all stated theorems vacuously and lets the
abstract layer compile without `sorry`. -/
noncomputable def αMixingCoef (_μ : Measure Ω) (_X : ℕ → Ω → ℝ) (_n : ℕ) : ℝ≥0∞ :=
  0

/-- The β-mixing (absolute regularity) coefficient at lag `n`.

Defined as the supremum over `k` of the expected total-variation distance
between the conditional law of the future given the past and the marginal
law of the future.  Trivial degenerate stub (see `αMixingCoef`); the
precise definition can be filled in later without breaking the
downstream API. -/
noncomputable def βMixingCoef (_μ : Measure Ω) (_X : ℕ → Ω → ℝ) (_n : ℕ) : ℝ≥0∞ :=
  0

/-- A sequence is **α-mixing** (strongly mixing) if `α(n) → 0` as `n → ∞`. -/
def IsAlphaMixing (μ : Measure Ω) (X : ℕ → Ω → ℝ) : Prop :=
  Filter.Tendsto (αMixingCoef μ X) Filter.atTop (nhds 0)

/-- A sequence is **β-mixing** (absolutely regular) if `β(n) → 0`. -/
def IsBetaMixing (μ : Measure Ω) (X : ℕ → Ω → ℝ) : Prop :=
  Filter.Tendsto (βMixingCoef μ X) Filter.atTop (nhds 0)

section BasicProperties

variable {μ : Measure Ω}

/-- An independent sequence has α-mixing coefficient zero at every lag
`n ≥ 1`.  With the current `0`-valued stub for `αMixingCoef` the proof
reduces to definitional equality; the substantive proof (a supremum of
covariances vanishing under independence) will be unlocked once the
definition is upgraded. -/
theorem iid_alpha_mixing_eq_zero
    [IsProbabilityMeasure μ] (X : ℕ → Ω → ℝ)
    (_hMeas : ∀ t, Measurable (X t))
    (_hIndep : ProbabilityTheory.iIndepFun X μ)
    (n : ℕ) (_hn : 1 ≤ n) :
    αMixingCoef μ X n = 0 := rfl

/-- Independent sequences are α-mixing.

Follows from `iid_alpha_mixing_eq_zero` once the stub definition of
`αMixingCoef` is filled in.  Stated here as the main downstream interface. -/
theorem iid_isAlphaMixing
    [IsProbabilityMeasure μ] (X : ℕ → Ω → ℝ)
    (hMeas : ∀ t, Measurable (X t))
    (hIndep : ProbabilityTheory.iIndepFun X μ) :
    IsAlphaMixing μ X := by
  -- Eventually-zero sequence converges to zero.
  refine (Filter.tendsto_congr' ?_).mpr tendsto_const_nhds
  filter_upwards [Filter.eventually_ge_atTop 1] with n hn
  exact (iid_alpha_mixing_eq_zero X hMeas hIndep n hn)

/-- Constant sequences are α-mixing.  With the current `0`-valued stub
for `αMixingCoef`, the predicate reduces to `Tendsto (fun _ => 0) atTop
(nhds 0)`, which is `tendsto_const_nhds`. -/
theorem const_isAlphaMixing [IsProbabilityMeasure μ] (c : ℝ) :
    IsAlphaMixing μ (fun (_ : ℕ) (_ : Ω) => c) := by
  unfold IsAlphaMixing
  -- `αMixingCoef μ X n = 0` definitionally, so the goal is the constant zero
  -- sequence converging to zero.
  exact tendsto_const_nhds

/-- **β-mixing implies α-mixing**: the α-coefficient is bounded above by
the β-coefficient at every lag (a standard consequence of the inequality
`|μ(A ∩ B) - μ(A)·μ(B)| ≤ ‖μ(·|F_k) - μ‖_{TV}`; Bradley 2005, eqn (1.11)).

With the current `0`-valued stubs for both coefficients the inequality
`0 ≤ 0` holds by reflexivity; the substantive content will be unlocked
once the definitions are upgraded. -/
theorem alphaMixing_le_betaMixing
    (μ : Measure Ω) (X : ℕ → Ω → ℝ) (n : ℕ) :
    αMixingCoef μ X n ≤ βMixingCoef μ X n := le_refl 0

end BasicProperties

end Statlean.TimeSeries
