#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from collections import OrderedDict
from pathlib import Path
from typing import Dict, List


def parse_promoted_ids(report_path: Path) -> List[str]:
    obj = json.loads(report_path.read_text(encoding="utf-8"))
    promoted = obj.get("promoted", []) or []
    ids: List[str] = []
    for item in promoted:
        theorem_id = str(item.get("id", "")).strip()
        if theorem_id and theorem_id not in ids:
            ids.append(theorem_id)
    return ids


def extract_blocks_by_id(source_text: str) -> Dict[str, str]:
    lines = source_text.splitlines(keepends=True)
    n = len(lines)
    i = 0
    out: Dict[str, str] = {}

    def starts_id_block(idx: int) -> bool:
        if idx + 1 >= n:
            return False
        return lines[idx].strip() == "/-" and lines[idx + 1].startswith("ID: ")

    def is_boundary(idx: int) -> bool:
        if idx >= n:
            return True
        if starts_id_block(idx):
            return True
        s = lines[idx].strip()
        return s in {"end FormalizationLayer", "end StatlibLayer", "end ThemeGenerated"}

    while i < n:
        if not starts_id_block(i):
            i += 1
            continue

        start = i
        theorem_id = lines[i + 1][len("ID: ") :].strip()

        j = i + 2
        while j < n and lines[j].strip() != "-/":
            j += 1
        if j >= n:
            break

        k = j + 1
        while k < n and lines[k].strip() == "":
            k += 1
        first_word = lines[k].lstrip().split()[0] if k < n and lines[k].strip() else ""
        if first_word not in ("theorem", "lemma", "def", "noncomputable", "/--"):
            i = k
            continue

        l = k + 1
        while l < n and not is_boundary(l):
            l += 1

        chunk = "".join(lines[start:l]).rstrip() + "\n\n"
        out[theorem_id] = chunk
        i = l

    return out


def infer_group_name(chunk: str) -> str:
    m_title = re.search(r"(?m)^Title:\s*(.+)$", chunk)
    m_kind = re.search(r"(?m)^Kind:\s*(.+)$", chunk)
    title = (m_title.group(1).strip() if m_title else "").lower()
    kind = (m_kind.group(1).strip() if m_kind else "").lower()
    sample = chunk[:2000].lower()
    text = f"{title}\n{kind}\n{sample}"

    # Concentration / probability keywords (check FIRST — more specific)
    conc_kw = [
        "berry", "esseen", "clt", "central limit", "concentration",
        "poincare", "poincaré", "log-sobolev", "efron-stein", "stein",
        "hoeffding", "azuma", "chernoff", "chebyshev", "markov",
        "bound", "inequality", "tail", "sub-gaussian", "subgaussian",
        "characteristic function", "charfun", "fourier",
        "iid", "i.i.d", "independent", "variance",
    ]
    if any(k in text for k in conc_kw):
        return "Concentration"

    mean_kw = [
        "fréchet", "frechet", "spd mean", "spd average", "determinant",
        "random element", "log-cholesky mean",
    ]
    geom_kw = [
        "lie group", "geodesic", "parallel transport", "curvature",
        "metric", "diffeomorphism", "cholesky", "differential", "manifold",
    ]

    if any(k in text for k in mean_kw):
        return "SPDMeans"
    if any(k in text for k in geom_kw):
        return "SPDGeometry"
    return "General"


def render_module(chunks: List[str]) -> str:
    header = (
        "import Mathlib\n\n"
        "/-! Auto-generated by theme/scripts/promote_to_statlib.py.\n"
        "Do not edit manually; rerun the promotion pipeline.\n"
        "-/\n\n"
        "open MeasureTheory ProbabilityTheory MeasureTheory.Measure\n\n"
        "namespace Statlean\n"
        "namespace AutoPromoted\n\n"
    )
    if not chunks:
        body = "-- no promoted declarations\n\n"
        footer = "end AutoPromoted\nend Statlean\n"
        return header + body + footer

    grouped: "OrderedDict[str, List[str]]" = OrderedDict()
    preferred_order = ["Concentration", "SPDGeometry", "SPDMeans", "General"]
    for g in preferred_order:
        grouped[g] = []

    for chunk in chunks:
        g = infer_group_name(chunk)
        if g not in grouped:
            grouped[g] = []
        grouped[g].append(chunk)

    parts: List[str] = []
    for g, group_chunks in grouped.items():
        if not group_chunks:
            continue
        parts.append(f"section {g}\n")
        parts.append(f"/-! Auto-promoted declarations for group: `{g}`. -/\n\n")
        parts.extend(group_chunks)
        parts.append(f"end {g}\n\n")

    footer = "end AutoPromoted\nend Statlean\n"
    return header + "".join(parts) + footer


def theorem_name_from_chunk(chunk: str) -> str:
    for line in chunk.splitlines():
        s = line.strip()
        for prefix in ("theorem ", "lemma ", "def ", "noncomputable def "):
            if s.startswith(prefix):
                name = s[len(prefix):].split(" : ", 1)[0].split(" {", 1)[0].split(" (", 1)[0].strip()
                return name
    return ""


def theorem_name_set_from_library(repo_root: Path, exclude_file: Path | None) -> set[str]:
    out: set[str] = set()
    statlean_dir = repo_root / "Statlean"
    if not statlean_dir.exists():
        return out

    for fp in statlean_dir.rglob("*.lean"):
        if exclude_file is not None and fp.resolve() == exclude_file.resolve():
            continue
        text = fp.read_text(encoding="utf-8")
        for m in re.finditer(r"(?m)^\s*(?:theorem|lemma|def|noncomputable\s+def)\s+([A-Za-z0-9_']+)\b", text):
            out.add(m.group(1))
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="Write promoted theorem blocks into Statlean module")
    ap.add_argument("--source-lean", required=True, help="Path to final generated Lean file")
    ap.add_argument("--promote-report", required=True, help="Path to promote_report.json")
    ap.add_argument("--repo-root", required=True, help="Repo root for duplicate checks")
    ap.add_argument("--output-module", required=True, help="Path to write candidate module")
    ap.add_argument("--exclude-module", default="", help="Module file to exclude from duplicate check, e.g. Statlean/AutoPromoted.lean")
    ap.add_argument("--summary-json", required=True, help="Path to write apply summary JSON")
    ap.add_argument("--allow-unresolved", action="store_true", help="Allow TODO markers in promoted blocks")
    args = ap.parse_args()

    source_lean = Path(args.source_lean)
    promote_report = Path(args.promote_report)
    repo_root = Path(args.repo_root)
    output_module = Path(args.output_module)
    exclude_module = Path(args.exclude_module) if args.exclude_module else None
    summary_json = Path(args.summary_json)

    source_text = source_lean.read_text(encoding="utf-8")
    promoted_ids = parse_promoted_ids(promote_report)
    blocks_by_id = extract_blocks_by_id(source_text)

    missing_ids = [tid for tid in promoted_ids if tid not in blocks_by_id]
    if missing_ids:
        raise SystemExit(f"missing promoted IDs in generated file: {', '.join(missing_ids)}")

    entries = []
    for tid in promoted_ids:
        chunk = blocks_by_id[tid]
        thm_name = theorem_name_from_chunk(chunk)
        if not thm_name:
            raise SystemExit(f"cannot parse theorem name for promoted id: {tid}")
        entries.append({"id": tid, "name": thm_name, "chunk": chunk})

    existing_names = theorem_name_set_from_library(repo_root, exclude_module)
    selected_entries = [e for e in entries if e["name"] not in existing_names]
    skipped_existing = [e for e in entries if e["name"] in existing_names]
    selected_chunks = [e["chunk"] for e in selected_entries]
    group_counts: Dict[str, int] = {}
    for e in selected_entries:
        g = infer_group_name(e["chunk"])
        group_counts[g] = group_counts.get(g, 0) + 1

    if not args.allow_unresolved:
        unresolved_ids = [e["id"] for e in selected_entries if "TODO_TRANSLATE_ID:" in e["chunk"]]
        if unresolved_ids:
            raise SystemExit(f"unresolved promoted IDs: {', '.join(unresolved_ids)}")

    output_module.parent.mkdir(parents=True, exist_ok=True)
    output_module.write_text(render_module(selected_chunks), encoding="utf-8")

    summary = {
        "source_lean": str(source_lean.resolve()),
        "promote_report": str(promote_report.resolve()),
        "repo_root": str(repo_root.resolve()),
        "output_module": str(output_module.resolve()),
        "exclude_module": str(exclude_module.resolve()) if exclude_module else "",
        "promoted_ids_all": promoted_ids,
        "promoted_ids_selected": [e["id"] for e in selected_entries],
        "promoted_ids_skipped_existing": [e["id"] for e in skipped_existing],
        "promoted_theorem_names_selected": [e["name"] for e in selected_entries],
        "promoted_theorem_names_skipped_existing": [e["name"] for e in skipped_existing],
        "group_counts_selected": group_counts,
        "promoted_count": len(promoted_ids),
        "module_decl_count": len(selected_chunks),
    }
    summary_json.parent.mkdir(parents=True, exist_ok=True)
    summary_json.write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False))


if __name__ == "__main__":
    main()
