import Statlean.Variance.ANOVA
import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.Independence.Integration
import Mathlib.MeasureTheory.Measure.FiniteMeasurePi
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Probability.CondVar
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Integral.Prod

/-! # Efron-Stein Inequality

## Main definitions
- `prodMeasure` — product probability measure
- `sigmaAlgExcept` — σ-algebra forgetting coordinate i
- `condExpExceptCoord` — conditional expectation averaging out coordinate i

## Main results (proved, zero sorry)
- `efron_stein_of_condVar_sum_bound` — Efron-Stein from condVar sum
- `efron_stein_unique_eq` — exact equality for single coordinate

See also `Statlean.Variance.ANOVA` for `sq_integral_le_integral_sq`,
`variance_marginals_le_variance_prod`, and other ANOVA infrastructure.

## Sorry gaps (2 sorry, blocked by missing Mathlib infrastructure)
- `condExp_condExp_comm_pi` — commutativity of conditional expectations on product spaces.
  **Blocked by**: Bochner Fubini for `Measure.pi` single-coordinate marginalization.
- `efron_stein_core_gen/hg_es` — Efron-Stein applied to `g = E[f|N]` on reduced index set.
  **Blocked by**: quotient reduction `∏_ι X → ∏_{ι\{i₀}} X` with Var/condVar transfer
  via `measurePreserving_piEquivPiSubtypeProd`. Rest of inductive step fully proved
  (sum splitting, i₀ term = 0, j≠i₀ comparison via `efron_stein_condVar_le_of_condExp`).

## Proved sorry (was h_main in efron_stein_condVar_le_of_condExp)
- `∫ Var[E[f|M]|N] ≤ ∫ Var[f|N]` now **fully proved** via:
  1. `setIntegral_condVar` converts both sides to squared-difference integrals
  2. Commutativity (`condExp_condExp_comm_pi`, sorry) + linearity (`condExp_sub`)
     gives ae equality `(E[f|M] - E[E[f|M]|N])² =ᵃᵉ (E[h|M])²` where `h = f - g`
  3. `integral_sq_condExp_le` (L² contraction) closes the gap
-/

open MeasureTheory ProbabilityTheory MeasurableSpace Finset

noncomputable section

variable {ι : Type*} [Fintype ι]
variable {X : ι → Type*} [∀ i, MeasurableSpace (X i)]
variable (μ : ∀ i, Measure (X i))

/-! ## Shared definitions -/

/-- The product probability measure on `∏ i, X i`. -/
abbrev prodMeasure : Measure (∀ i, X i) := Measure.pi μ

/-- The sigma-algebra generated by all coordinates except `i`. -/
def sigmaAlgExcept (i : ι) : MeasurableSpace (∀ j, X j) :=
  ⨆ j ∈ ({i}ᶜ : Set ι), MeasurableSpace.comap (fun x => x j) (‹∀ j, MeasurableSpace (X j)› j)

set_option linter.unusedSectionVars false in
set_option linter.unusedFintypeInType false in
lemma sigmaAlgExcept_le (i : ι) :
    sigmaAlgExcept (X := X) i ≤ (inferInstance : MeasurableSpace (∀ j, X j)) := by
  classical
  refine iSup₂_le ?_
  intro j hj
  exact le_iSup (fun a : ι =>
    MeasurableSpace.comap (fun x : (∀ b, X b) => x a)
      (inferInstance : MeasurableSpace (X a))) j

set_option linter.unusedSectionVars false in
set_option linter.unusedFintypeInType false in
lemma sigmaAlgExcept_eq_bot [Unique ι] (i : ι) :
    sigmaAlgExcept (X := X) i = (⊥ : MeasurableSpace (∀ j, X j)) := by
  have hcomp : ({i}ᶜ : Set ι) = ∅ := by
    ext j
    simp [Subsingleton.elim j i]
  simp [sigmaAlgExcept, hcomp]

/-- Conditional expectation of `f` given all coordinates except `i`. -/
def condExpExceptCoord (i : ι) (f : (∀ j, X j) → ℝ) :
    (∀ j, X j) → ℝ :=
  (Measure.pi μ)[f | sigmaAlgExcept i]

lemma efron_stein_isEmpty [IsEmpty ι]
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (_hf : MemLp f 2 (Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] := by
  simp [variance_pi_of_isEmpty μ f]

/-! ## Efron-Stein proved declarations -/

theorem efron_stein_of_integral_bound
    (f : (∀ j, X j) → ℝ)
    (hES :
      Var[f; Measure.pi μ] ≤
        ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by
  exact hES

lemma efron_stein_term_eq_integral_condVar_exceptCoord
    [∀ i, IsProbabilityMeasure (μ i)]
    (i : ι) (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) =
      (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] := by
  classical
  have hm : sigmaAlgExcept i ≤ (inferInstance : MeasurableSpace (∀ j, X j)) :=
    sigmaAlgExcept_le (X := X) i
  have hfi : Integrable (fun ω => (f ω - condExpExceptCoord μ i f ω) ^ 2) (Measure.pi μ) := by
    exact (hf.sub hf.condExp).integrable_sq
  calc
    ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ)
        = ∫ ω in Set.univ, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by simp
    _ = ∫ ω in Set.univ, (Var[f; Measure.pi μ | sigmaAlgExcept i]) ω ∂(Measure.pi μ) := by
      symm
      exact setIntegral_condVar (m := sigmaAlgExcept i) (hm := hm)
        (μ := Measure.pi μ) (X := f) (s := Set.univ) hfi (by simp)
    _ = (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] := by simp

lemma efron_stein_rhs_eq_sum_integral_condVar
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    (∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ))
      =
    (∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]]) := by
  classical
  refine Finset.sum_congr rfl ?_
  intro i hi
  simpa using efron_stein_term_eq_integral_condVar_exceptCoord (μ := μ) i f hf

theorem efron_stein_of_condVar_sum_bound
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ))
    (hCondVar :
      Var[f; Measure.pi μ] ≤
        ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]]) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by
  have hEq :=
    efron_stein_rhs_eq_sum_integral_condVar (μ := μ) f hf
  calc
    Var[f; Measure.pi μ]
      ≤ ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] := hCondVar
    _ = ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by
      simpa [eq_comm] using hEq

theorem efron_stein_to_condVar_sum_bound
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ))
    (hES :
      Var[f; Measure.pi μ] ≤
        ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] := by
  simpa [efron_stein_rhs_eq_sum_integral_condVar (μ := μ) f hf] using hES

theorem efron_stein_iff_condVar_sum_bound
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    (Var[f; Measure.pi μ] ≤
        ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ))
      ↔
    (Var[f; Measure.pi μ] ≤
        ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]]) := by
  constructor
  · intro hES
    exact efron_stein_to_condVar_sum_bound (μ := μ) f hf hES
  · intro hCondVar
    exact efron_stein_of_condVar_sum_bound (μ := μ) f hf hCondVar

lemma efron_stein_rhs_nonneg
    (f : (∀ j, X j) → ℝ) :
    0 ≤ ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by
  classical
  refine Finset.sum_nonneg ?_
  intro i hi
  exact integral_nonneg (fun _ => sq_nonneg _)

theorem efron_stein_unique_eq
    [Unique ι]
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    Var[f; Measure.pi μ] =
      ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by
  classical
  have hsig : sigmaAlgExcept (default : ι) = (⊥ : MeasurableSpace (∀ j, X j)) :=
    sigmaAlgExcept_eq_bot (X := X) (default : ι)
  have hterm :
      ∫ ω, (f ω - condExpExceptCoord μ (default : ι) f ω) ^ 2 ∂(Measure.pi μ) =
        Var[f; Measure.pi μ] := by
    calc
      ∫ ω, (f ω - condExpExceptCoord μ (default : ι) f ω) ^ 2 ∂(Measure.pi μ)
          = (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept (default : ι)]] :=
        efron_stein_term_eq_integral_condVar_exceptCoord (μ := μ) (default : ι) f hf
      _ = (Measure.pi μ)[Var[f; Measure.pi μ | (⊥ : MeasurableSpace (∀ j, X j))]] := by
        simp [hsig]
      _ = ∫ ω, (Var[f; Measure.pi μ | (⊥ : MeasurableSpace (∀ j, X j))]) ω ∂(Measure.pi μ) := by
        rfl
      _ = ∫ ω, Var[f; Measure.pi μ] ∂(Measure.pi μ) := by
        simp [condVar_bot (μ := Measure.pi μ) (hX := hf.aemeasurable)]
      _ = Var[f; Measure.pi μ] := by simp
  have hsum :
      (∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ)) =
      ∫ ω, (f ω - condExpExceptCoord μ (default : ι) f ω) ^ 2 ∂(Measure.pi μ) := by
    exact (Fintype.sum_unique (f := fun i : ι =>
      ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ)))
  rw [hsum, hterm]

theorem efron_stein_unique
    [Unique ι]
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by
  exact (efron_stein_unique_eq (μ := μ) f hf).le

lemma efron_stein_core_unique [Unique ι]
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] :=
  (efron_stein_iff_condVar_sum_bound (μ := μ) f hf).mp (efron_stein_unique (μ := μ) f hf)

/-! ## Sorry-bearing declarations -/

/-! ### Commutativity of conditional expectations on product spaces

On `Measure.pi μ` with independent coordinates, conditional expectations
`E[·|sigmaAlgExcept i₀]` and `E[·|sigmaAlgExcept j]` commute for `j ≠ i₀`.
This is because these conditional expectations correspond to integrating out
single coordinates, and by Fubini the order of integration doesn't matter.

**Status**: sorry — requires Bochner Fubini for `Measure.pi` single-coordinate
marginalization. Mathlib has `lmarginal` (for `ℝ≥0∞`) and
`measurePreserving_piEquivPiSubtypeProd`, but the Bochner integral version is not
yet available.
-/

set_option linter.unusedSectionVars false in
private lemma condExp_condExp_comm_pi
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ) (hf : Integrable f (Measure.pi μ))
    (i₀ j : ι) (hij : j ≠ i₀) :
    (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept i₀] | sigmaAlgExcept j] =ᵐ[Measure.pi μ]
      (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept j] | sigmaAlgExcept i₀] := by
  sorry

/-! ### Variance contraction under conditional expectation

For `g = E[f | sigmaAlgExcept i₀]` and `j ≠ i₀`:
  `∫ Var[g | σ(j)] ≤ ∫ Var[f | σ(j)]`

**Proof** (using 4 applications of LTV + commutativity + L² contraction):
Let M = sigmaAlgExcept j, N = sigmaAlgExcept i₀, g = E[f|N], h = f - g.

1. LTV gives: ∫ Var[g|M] = Var[g] - Var[E[g|M]]
2. LTV gives: ∫ Var[f|M] = Var[f] - Var[E[f|M]]
3. LTV gives: Var[g] = Var[f] - ∫ Var[f|N]
4. Commutativity: E[g|M] =ᵃᵉ E[E[f|M]|N]
5. LTV gives: Var[E[f|M]] = ∫ Var[E[f|M]|N] + Var[E[E[f|M]|N]]
6. From (4)+(5): Var[E[f|M]] - Var[E[g|M]] = ∫ Var[E[f|M]|N]
7. Substituting (3)+(6) into (1)-(2):
   ∫ Var[g|M] - ∫ Var[f|M] = ∫ Var[E[f|M]|N] - ∫ Var[f|N]
8. Key claim: ∫ Var[E[f|M]|N] ≤ ∫ Var[f|N]
   Proof: With commutativity, ∫ Var[E[f|M]|N] = ∫ (E[h|M])²
          and ∫ Var[f|N] = ∫ h², where h = f - E[f|N].
          Then ∫ (E[h|M])² ≤ ∫ h² by L² contraction of conditional expectation.
-/

/-- Conditional expectation is an L² contraction: `∫ (E[h|m])² ≤ ∫ h²`.
This follows from `Var[E[h|m]] ≤ Var[h]` (law of total variance) and `E[E[h|m]] = E[h]`. -/
private lemma integral_sq_condExp_le
    [∀ i, IsProbabilityMeasure (μ i)]
    (h : (∀ j, X j) → ℝ) (hh : MemLp h 2 (Measure.pi μ))
    (m : MeasurableSpace (∀ j, X j)) (hm : m ≤ (MeasurableSpace.pi : MeasurableSpace (∀ j, X j))) :
    ∫ ω, ((Measure.pi μ)[h | m] ω) ^ 2 ∂(Measure.pi μ) ≤
      ∫ ω, h ω ^ 2 ∂(Measure.pi μ) := by
  have hh_int := hh.integrable (by norm_num)
  have hPh : MemLp ((Measure.pi μ)[h | m]) 2 (Measure.pi μ) := hh.condExp
  -- Var[E[h|m]] ≤ Var[h] from LTV
  have hvar_le : Var[(Measure.pi μ)[h | m]; Measure.pi μ] ≤ Var[h; Measure.pi μ] := by
    have hltv := integral_condVar_add_variance_condExp hm (μ := Measure.pi μ) hh
    have hnn : 0 ≤ ∫ ω, (Var[h; Measure.pi μ | m]) ω ∂(Measure.pi μ) := by
      exact integral_nonneg_of_ae (condExp_nonneg (ae_of_all _ fun ω => sq_nonneg _))
    linarith
  -- ∫ (E[h|m])² = Var[E[h|m]] + (E[h])² by variance_eq_sub
  have hPh_sq : ∫ ω, ((Measure.pi μ)[h | m] ω) ^ 2 ∂(Measure.pi μ) =
      Var[(Measure.pi μ)[h | m]; Measure.pi μ] +
        (∫ ω, (Measure.pi μ)[h | m] ω ∂(Measure.pi μ)) ^ 2 := by
    rw [variance_eq_sub hPh]; simp [Pi.pow_apply]
  -- ∫ h² = Var[h] + (E[h])² by variance_eq_sub
  have hh_sq : ∫ ω, h ω ^ 2 ∂(Measure.pi μ) =
      Var[h; Measure.pi μ] + (∫ ω, h ω ∂(Measure.pi μ)) ^ 2 := by
    rw [variance_eq_sub hh]; simp [Pi.pow_apply]
  -- E[E[h|m]] = E[h] (tower property)
  have hmean_eq : ∫ ω, (Measure.pi μ)[h | m] ω ∂(Measure.pi μ) =
      ∫ ω, h ω ∂(Measure.pi μ) := by
    exact integral_condExp hm
  rw [hPh_sq, hh_sq, hmean_eq]
  linarith

private lemma efron_stein_condVar_le_of_condExp
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ) (hf : MemLp f 2 (Measure.pi μ))
    (i₀ j : ι) (hij : j ≠ i₀) :
    (Measure.pi μ)[Var[condExpExceptCoord μ i₀ f; Measure.pi μ | sigmaAlgExcept j]] ≤
      (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept j]] := by
  classical
  set M := sigmaAlgExcept (X := X) j
  set N := sigmaAlgExcept (X := X) i₀
  set g := condExpExceptCoord μ i₀ f  -- = E[f|N]
  set P := Measure.pi μ
  have hM : M ≤ (MeasurableSpace.pi : MeasurableSpace (∀ j, X j)) := sigmaAlgExcept_le (X := X) j
  have hN : N ≤ (MeasurableSpace.pi : MeasurableSpace (∀ j, X j)) := sigmaAlgExcept_le (X := X) i₀
  have hg : MemLp g 2 P := hf.condExp
  have hfM : MemLp (P[f | M]) 2 P := hf.condExp
  -- LTV: ∫ Var[g|M] + Var[E[g|M]] = Var[g]
  have hltv_gM := integral_condVar_add_variance_condExp hM (μ := P) hg
  -- LTV: ∫ Var[f|M] + Var[E[f|M]] = Var[f]
  have hltv_fM := integral_condVar_add_variance_condExp hM (μ := P) hf
  -- LTV: ∫ Var[f|N] + Var[g] = Var[f]
  have hltv_fN := integral_condVar_add_variance_condExp hN (μ := P) hf
  -- LTV: ∫ Var[E[f|M]|N] + Var[E[E[f|M]|N]] = Var[E[f|M]]
  have hltv_fMN := integral_condVar_add_variance_condExp hN (μ := P) hfM
  -- Commutativity: E[g|M] = E[E[f|N]|M] =ᵃᵉ E[E[f|M]|N]
  have hcomm : P[g | M] =ᵐ[P] P[P[f | M] | N] := by
    exact condExp_condExp_comm_pi μ f (hf.integrable (by norm_num)) i₀ j hij
  -- Var[E[g|M]] = Var[E[E[f|M]|N]] (from commutativity)
  have hvar_comm : Var[P[g | M]; P] = Var[P[P[f | M] | N]; P] :=
    variance_congr hcomm
  -- ∫ Var[f|N] ≥ 0
  have hnn_fN : 0 ≤ P[Var[f; P | N]] := by
    exact integral_nonneg_of_ae (condExp_nonneg (ae_of_all _ fun ω => sq_nonneg _))
  -- ∫ Var[E[f|M]|N] ≥ 0
  have hnn_fMN : 0 ≤ P[Var[P[f | M]; P | N]] := by
    exact integral_nonneg_of_ae (condExp_nonneg (ae_of_all _ fun ω => sq_nonneg _))
  -- Key: from LTV equations, algebraically derive the bound
  -- ∫ Var[g|M] = Var[g] - Var[E[g|M]]
  --            = (Var[f] - ∫ Var[f|N]) - (Var[E[f|M]] - ∫ Var[E[f|M]|N])
  --            = ∫ Var[f|M] + ∫ Var[E[f|M]|N] - ∫ Var[f|N]
  -- So: ∫ Var[g|M] ≤ ∫ Var[f|M] iff ∫ Var[E[f|M]|N] ≤ ∫ Var[f|N]
  -- The latter follows from integral_sq_condExp_le.
  -- But we need to relate ∫ Var[E[f|M]|N] to ∫ (E[h|M])² and ∫ Var[f|N] to ∫ h².
  -- This requires the commutativity step.
  -- For now, we prove the algebraic part and use the nonnegativity bounds.
  -- From equations: ∫ Var[g|M] - ∫ Var[f|M]
  -- = (Var[g] - Var[E[g|M]]) - (Var[f] - Var[E[f|M]])
  -- = -(Var[f] - Var[g]) + (Var[E[f|M]] - Var[E[g|M]])
  -- = -∫ Var[f|N] + (Var[E[f|M]] - Var[E[E[f|M]|N]])     [using hvar_comm]
  -- = -∫ Var[f|N] + ∫ Var[E[f|M]|N]                        [using hltv_fMN]
  -- ≤ 0  iff  ∫ Var[E[f|M]|N] ≤ ∫ Var[f|N]
  -- The latter holds because ∫ Var[X|N] = Var[X] - Var[E[X|N]]
  -- and for X = E[f|M]: Var[E[f|M]] ≤ Var[f] and Var[E[E[f|M]|N]] ≥ 0.
  -- Actually we need a tighter bound. Let's use integral_sq_condExp_le.
  -- Using commutativity: ∫ Var[E[f|M]|N] and ∫ Var[f|N] can be related
  -- to ∫ (E[h|M])² and ∫ h² where h = f - E[f|N].
  -- For now, we use the algebraic bound directly.
  -- ∫ Var[E[f|M]|N] = Var[E[f|M]] - Var[E[E[f|M]|N]]
  --                  = Var[E[f|M]] - Var[E[g|M]]  (commutativity)
  -- ∫ Var[f|N] = Var[f] - Var[g]
  -- Need: Var[E[f|M]] - Var[E[g|M]] ≤ Var[f] - Var[g]
  -- i.e., Var[E[f|M]] - Var[f] ≤ Var[E[g|M]] - Var[g]
  -- i.e., -(Var[f] - Var[E[f|M]]) ≤ -(Var[g] - Var[E[g|M]])
  -- i.e., Var[g] - Var[E[g|M]] ≤ Var[f] - Var[E[f|M]]
  -- i.e., ∫ Var[g|M] ≤ ∫ Var[f|M]  (which is what we want!)
  -- So the algebra is CIRCULAR when expanded this way.
  -- We break the cycle with integral_sq_condExp_le:
  -- ∫ Var[E[f|M]|N] ≤ ∫ Var[f|N] because (with commutativity):
  -- ∫ Var[E[f|M]|N] = ∫ (E[f|M] - E[E[f|M]|N])²
  --                  = ∫ (E[f|M] - E[g|M])²     (comm: E[E[f|M]|N] = E[g|M])
  --                  = ∫ (E[f-g|M])²
  --                  = ∫ (E[h|M])²               (h = f - g)
  -- ∫ Var[f|N] = ∫ (f - E[f|N])² = ∫ h²
  -- And ∫ (E[h|M])² ≤ ∫ h² by integral_sq_condExp_le.
  -- We prove this chain via setIntegral_condVar and integral rewrites.
  -- For the algebraic combination, we use linarith with the 4 LTV equations.
  have h_main : P[Var[P[f | M]; P | N]] ≤ P[Var[f; P | N]] := by
    -- ∫ Var[E[f|M]|N] = Var[E[f|M]] - Var[E[E[f|M]|N]]  (from hltv_fMN)
    -- ∫ Var[f|N] = Var[f] - Var[g]                         (from hltv_fN)
    -- Need: Var[E[f|M]] - Var[E[E[f|M]|N]] ≤ Var[f] - Var[g]
    -- i.e., Var[E[f|M]] + Var[g] ≤ Var[f] + Var[E[E[f|M]|N]]
    -- Using integral_sq_condExp_le on h = f - g w.r.t. M:
    -- ∫ (E[h|M])² ≤ ∫ h²
    -- We need to relate this to the variance terms.
    -- ∫ (E[h|M])² = Var[E[h|M]] + (E[h])²  (variance_eq_sub)
    -- ∫ h² = Var[h] + (E[h])²               (variance_eq_sub)
    -- E[h] = E[f-g] = E[f] - E[g] = E[f] - E[E[f|N]] = E[f] - E[f] = 0
    -- Wait, E[g] = E[E[f|N]] = E[f], so E[h] = E[f-g] = 0.
    -- So: ∫ (E[h|M])² = Var[E[h|M]]
    --     ∫ h² = Var[h]
    -- And: Var[E[h|M]] ≤ Var[h] from integral_sq_condExp_le (or LTV directly)
    -- Now relate to original terms:
    -- h = f - g, E[h|M] = E[f|M] - E[g|M]
    -- Var[h] = Var[f - g]
    -- Var[E[h|M]] = Var[E[f|M] - E[g|M]] = Var[E[f-g|M]]
    -- With commutativity: E[g|M] = E[E[f|N]|M] = E[E[f|M]|N]
    -- So E[f|M] - E[g|M] = E[f|M] - E[E[f|M]|N]
    -- And Var[E[h|M]] = Var[E[f|M] - E[E[f|M]|N]]
    -- But ∫ Var[E[f|M]|N] = ∫ (E[f|M] - E[E[f|M]|N])²  (setIntegral_condVar on Set.univ)
    -- By variance_of_integral_eq_zero (since E[E[f|M] - E[E[f|M]|N]] = 0):
    -- Var[E[f|M] - E[E[f|M]|N]] = ∫ (E[f|M] - E[E[f|M]|N])²
    -- So ∫ Var[E[f|M]|N] = Var[E[f|M] - E[E[f|M]|N]] = Var[E[h|M]]
    -- Similarly: ∫ Var[f|N] = ∫ (f - E[f|N])² = ∫ h²
    -- Since E[h] = 0: ∫ h² = Var[h]
    -- And: Var[E[h|M]] ≤ Var[h] → ∫ Var[E[f|M]|N] ≤ ∫ Var[f|N]
    -- This can be proved using integral_sq_condExp_le on h w.r.t. M.
    set h := f - g with hh_def
    have hh : MemLp h 2 P := hf.sub hg
    have hh_int : Integrable h P := hh.integrable (by norm_num)
    -- h = f - E[f|N], so E[h|M] = E[f-g|M] = E[f|M] - E[g|M]
    -- E[h|M] =ᵃᵉ E[f|M] - E[g|M]
    have hEhM : P[h | M] =ᵐ[P] P[f | M] - P[g | M] :=
      condExp_sub (hf.integrable (by norm_num)) (hg.integrable (by norm_num)) M
    -- Use integral_sq_condExp_le: ∫ (E[h|M])² ≤ ∫ h²
    have h_contraction := integral_sq_condExp_le μ h hh M hM
    -- Step 1: P[Var[f|N]] = ∫ h² via setIntegral_condVar
    have hfi_N : Integrable (fun ω => (f ω - P[f | N] ω) ^ 2) P :=
      (hf.sub hf.condExp).integrable_sq
    have h_rhs : P[Var[f; P | N]] = ∫ ω, (h ω) ^ 2 ∂P := by
      rw [show P[Var[f; P | N]] = ∫ ω in Set.univ, (Var[f; P | N]) ω ∂P from by simp]
      rw [setIntegral_condVar (hm := hN) hfi_N (by simp)]
      simp only [Measure.restrict_univ]
      -- h = f - g = f - P[f|N], so (f ω - P[f|N] ω)² = h ω²
      rfl
    -- Step 2: P[Var[P[f|M]|N]] = ∫ (P[f|M] - P[P[f|M]|N])² via setIntegral_condVar
    have hfMi_N : Integrable (fun ω => (P[f | M] ω - P[P[f | M] | N] ω) ^ 2) P :=
      (hfM.sub hfM.condExp).integrable_sq
    have h_lhs_step1 : P[Var[P[f | M]; P | N]] =
        ∫ ω, (P[f | M] ω - P[P[f | M] | N] ω) ^ 2 ∂P := by
      rw [show P[Var[P[f | M]; P | N]] =
        ∫ ω in Set.univ, (Var[P[f | M]; P | N]) ω ∂P from by simp]
      rw [setIntegral_condVar (hm := hN) hfMi_N (by simp)]
      simp
    -- Step 3: (P[f|M] - P[P[f|M]|N])² =ᵃᵉ (P[h|M])² using commutativity
    -- hcomm : P[g|M] =ᵃᵉ P[P[f|M]|N], so P[P[f|M]|N] =ᵃᵉ P[g|M]
    -- hEhM : P[h|M] =ᵃᵉ P[f|M] - P[g|M]
    -- So P[f|M] - P[P[f|M]|N] =ᵃᵉ P[f|M] - P[g|M] =ᵃᵉ P[h|M]
    have h_ae_eq : (fun ω => (P[f | M] ω - P[P[f | M] | N] ω) ^ 2) =ᵐ[P]
        (fun ω => (P[h | M] ω) ^ 2) := by
      filter_upwards [hcomm.symm, hEhM] with ω hcomm_ω hEhM_ω
      simp only [Pi.sub_apply] at hEhM_ω
      rw [hcomm_ω, hEhM_ω]
    have h_lhs : P[Var[P[f | M]; P | N]] = ∫ ω, (P[h | M] ω) ^ 2 ∂P := by
      rw [h_lhs_step1]
      exact integral_congr_ae h_ae_eq
    -- Combine: P[Var[P[f|M]|N]] = ∫ (P[h|M])² ≤ ∫ h² = P[Var[f|N]]
    rw [h_lhs, h_rhs]
    exact h_contraction
  -- From h_main + LTV equations (algebra verified, see docstring above):
  -- ∫ Var[g|M] = Var[g] - Var[E[g|M]]
  -- ∫ Var[f|M] = Var[f] - Var[E[f|M]]
  -- diff = (Var[g] - Var[f]) + (Var[E[f|M]] - Var[E[g|M]])
  --      = -∫ Var[f|N] + ∫ Var[E[f|M]|N]  (using hvar_comm + hltv_fMN)
  --      ≤ 0  (from h_main)
  -- Normalize hltv_fN: P[f|N] = g definitionally (g = condExpExceptCoord μ i₀ f = P[f|N])
  -- linarith cannot see through definitional equality, so we rewrite explicitly.
  have hgN_eq : P[f | N] = g := rfl
  rw [hgN_eq] at hltv_fN
  -- Now hltv_fN : P[Var[f;P|N]] + Var[g;P] = Var[f;P]
  -- The algebra:
  -- P[Var[g|M]] = Var[g] - Var[E[g|M]]                          (from hltv_gM)
  --            = (Var[f] - P[Var[f|N]]) - Var[E[P[f|M]|N]]      (from hltv_fN, hvar_comm)
  --            = (Var[f] - P[Var[f|N]]) - (Var[P[f|M]] - P[Var[P[f|M]|N]])  (from hltv_fMN)
  -- P[Var[f|M]] = Var[f] - Var[P[f|M]]                          (from hltv_fM)
  -- Difference = P[Var[P[f|M]|N]] - P[Var[f|N]] ≤ 0             (from h_main)
  linarith [hltv_gM, hltv_fM, hltv_fN, hltv_fMN, hvar_comm, h_main]

private theorem efron_stein_core_gen (n : ℕ) :
    ∀ {ι : Type*} [Fintype ι]
      {X : ι → Type*} [∀ i, MeasurableSpace (X i)]
      (μ : ∀ i, Measure (X i)) [∀ i, IsProbabilityMeasure (μ i)]
      (f : (∀ j, X j) → ℝ),
      Fintype.card ι = n →
      MemLp f 2 (Measure.pi μ) →
      Var[f; Measure.pi μ] ≤
        ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] := by
  induction n with
  | zero =>
    intro ι _ X _ μ _ f hn hf
    haveI : IsEmpty ι := Fintype.card_eq_zero_iff.mp hn
    simp [variance_pi_of_isEmpty μ f]
  | succ n ih =>
    intro ι _ X _ μ _ f hn hf
    classical
    have hpos : 0 < Fintype.card ι := hn ▸ Nat.succ_pos n
    obtain ⟨i₀⟩ : Nonempty ι := Fintype.card_pos_iff.mp hpos
    set g := condExpExceptCoord μ i₀ f with hg_def
    have hg : MemLp g 2 (Measure.pi μ) := hf.condExp
    have hltv : (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i₀]] +
        Var[g; Measure.pi μ] = Var[f; Measure.pi μ] :=
      integral_condVar_add_variance_condExp (sigmaAlgExcept_le (X := X) i₀)
        (μ := Measure.pi μ) hf
    have hcondExp_g : (Measure.pi μ)[g | sigmaAlgExcept i₀] = g :=
      condExp_of_stronglyMeasurable (sigmaAlgExcept_le (X := X) i₀)
        stronglyMeasurable_condExp (hg.integrable (by norm_num))
    have hltv_g : (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept i₀]] = 0 := by
      have hltv2 := integral_condVar_add_variance_condExp (sigmaAlgExcept_le (X := X) i₀)
        (μ := Measure.pi μ) hg
      simp only [hcondExp_g] at hltv2
      linarith [variance_nonneg g (Measure.pi μ)]
    have hsum_f :
        ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] =
        (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i₀]] +
        ∑ j ∈ Finset.univ.erase i₀,
          (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept j]] :=
      (Finset.sum_erase_add Finset.univ _ (Finset.mem_univ i₀)).symm.trans (add_comm _ _)
    -- Efron-Stein for g: Var[g] ≤ ∑ j, E[Var[g|σ_j]]
    -- g is (sigmaAlgExcept i₀)-measurable, so effectively depends on n coordinates.
    -- We use E-S for g on the same space, then split and bound.
    have hg_es : Var[g; Measure.pi μ] ≤
        ∑ j : ι, (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] := by
      -- Apply IH to g viewed on the reduced index type {j | j ≠ i₀}.
      -- g = E[f|sigmaAlgExcept i₀] is strongly measurable w.r.t. sigmaAlgExcept i₀,
      -- meaning it does not depend on coordinate i₀.
      -- The dimension reduction requires:
      -- 1. Constructing an equivalent function on ∏_{j≠i₀} X_j
      -- 2. Showing variance and condVar transfer through the equivalence
      -- 3. Applying ih with Fintype.card {j | j ≠ i₀} = n
      -- This infrastructure (Bochner Fubini for Measure.pi marginals)
      -- is the same blocker as condExp_condExp_comm_pi.
      sorry
    -- Split the g sum and use hltv_g for the i₀ term
    have hg_sum_split :
        ∑ j : ι, (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] =
        (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept i₀]] +
        ∑ j ∈ Finset.univ.erase i₀,
          (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] :=
      (Finset.sum_erase_add Finset.univ _ (Finset.mem_univ i₀)).symm.trans (add_comm _ _)
    -- For each j ≠ i₀, use efron_stein_condVar_le_of_condExp
    have hg_le_f : ∀ j ∈ Finset.univ.erase i₀,
        (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] ≤
        (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept j]] := by
      intro j hj
      have hjne : j ≠ i₀ := Finset.ne_of_mem_erase hj
      exact efron_stein_condVar_le_of_condExp μ f hf i₀ j hjne
    -- Combine
    have hg_bound : Var[g; Measure.pi μ] ≤
        ∑ j ∈ Finset.univ.erase i₀,
          (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept j]] := by
      calc Var[g; Measure.pi μ]
          ≤ ∑ j : ι, (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] := hg_es
        _ = (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept i₀]] +
            ∑ j ∈ Finset.univ.erase i₀,
              (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] := hg_sum_split
        _ = 0 + ∑ j ∈ Finset.univ.erase i₀,
              (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] := by
            rw [hltv_g]
        _ = ∑ j ∈ Finset.univ.erase i₀,
              (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] := by
            ring
        _ ≤ ∑ j ∈ Finset.univ.erase i₀,
              (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept j]] :=
            Finset.sum_le_sum hg_le_f
    linarith [hltv, hg_bound, hsum_f.ge]

theorem efron_stein_core
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] :=
  efron_stein_core_gen (Fintype.card ι) μ f rfl hf

lemma efron_stein_anova_key
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    ∑ i : ι,
      Var[(Measure.pi μ)[f | sigmaAlgExcept i]; Measure.pi μ] ≤
    ((Fintype.card ι : ℝ) - 1) * Var[f; Measure.pi μ] := by
  have hltv : ∀ i : ι,
      (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] +
        Var[(Measure.pi μ)[f | sigmaAlgExcept i]; Measure.pi μ] = Var[f; Measure.pi μ] :=
    fun i => integral_condVar_add_variance_condExp (sigmaAlgExcept_le (X := X) i)
              (μ := Measure.pi μ) hf
  have hsum :
      (∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]]) +
        (∑ i : ι, Var[(Measure.pi μ)[f | sigmaAlgExcept i]; Measure.pi μ]) =
        (Fintype.card ι : ℝ) * Var[f; Measure.pi μ] := by
    rw [← Finset.sum_add_distrib]
    simp_rw [hltv]
    simp [Finset.sum_const, nsmul_eq_mul]
  have hES := efron_stein_core (μ := μ) f hf
  linarith

theorem efron_stein
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) :=
  efron_stein_of_condVar_sum_bound (μ := μ) f hf (efron_stein_core (μ := μ) f hf)

end
