import Statlean.Variance.ANOVA
import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.Independence.Integration
import Mathlib.MeasureTheory.Measure.FiniteMeasurePi
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Probability.CondVar
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Integral.Prod
import Mathlib.Probability.ConditionalExpectation
import Mathlib.MeasureTheory.Function.FactorsThrough

/-! # Efron-Stein Inequality

## Main definitions
- `prodMeasure` — product probability measure
- `sigmaAlgExcept` — σ-algebra forgetting coordinate i
- `condExpExceptCoord` — conditional expectation averaging out coordinate i

## Main results (proved, zero sorry)
- `efron_stein_of_condVar_sum_bound` — Efron-Stein from condVar sum
- `efron_stein_unique_eq` — exact equality for single coordinate

See also `Statlean.Variance.ANOVA` for `sq_integral_le_integral_sq`,
`variance_marginals_le_variance_prod`, and other ANOVA infrastructure.

## Key techniques
- `hhtil_condExp` — `htil =ᵃᵉ[P'] P'[gtil|M']` proved via Dynkin π-λ on the big space:
  Define `M'_full = comap restrict M'`, build π-system from `M'_full × σ_{i₀} × σ_j`,
  show integral equality on each rectangle factor using independence + tower property,
  extend via `induction_on_inter`, transfer to small space via `ae_map_iff`.

## Proved results
- `condExp_condExp_comm_pi` — **fully proved** via Dynkin π-λ theorem:
  Decompose product σ-algebra into π-system {A∩B∩C : A ∈ σ_{ij}, B ∈ σ_{i₀}, C ∈ σ_j},
  show both sides have equal set integrals on rectangles using independence +
  `condExp_indep_eq` + `setIntegral_condExp`, then extend via `induction_on_inter`.
- `∫ Var[E[f|M]|N] ≤ ∫ Var[f|N]` — **fully proved** via:
  1. `setIntegral_condVar` converts both sides to squared-difference integrals
  2. Commutativity (`condExp_condExp_comm_pi`) + linearity (`condExp_sub`)
     gives ae equality `(E[f|M] - E[E[f|M]|N])² =ᵃᵉ (E[h|M])²` where `h = f - g`
  3. `integral_sq_condExp_le` (L² contraction) closes the gap
-/

open MeasureTheory ProbabilityTheory MeasurableSpace Finset

noncomputable section

variable {ι : Type*} [Fintype ι]
variable {X : ι → Type*} [∀ i, MeasurableSpace (X i)]
variable (μ : ∀ i, Measure (X i))

/-! ## Shared definitions -/

/-- The product probability measure on `∏ i, X i`. -/
abbrev prodMeasure : Measure (∀ i, X i) := Measure.pi μ

/-- The sigma-algebra generated by all coordinates except `i`. -/
def sigmaAlgExcept (i : ι) : MeasurableSpace (∀ j, X j) :=
  ⨆ j ∈ ({i}ᶜ : Set ι), MeasurableSpace.comap (fun x => x j) (‹∀ j, MeasurableSpace (X j)› j)

set_option linter.unusedSectionVars false in
set_option linter.unusedFintypeInType false in
lemma sigmaAlgExcept_le (i : ι) :
    sigmaAlgExcept (X := X) i ≤ (inferInstance : MeasurableSpace (∀ j, X j)) := by
  classical
  refine iSup₂_le ?_
  intro j hj
  exact le_iSup (fun a : ι =>
    MeasurableSpace.comap (fun x : (∀ b, X b) => x a)
      (inferInstance : MeasurableSpace (X a))) j

set_option linter.unusedSectionVars false in
set_option linter.unusedFintypeInType false in
lemma sigmaAlgExcept_eq_bot [Unique ι] (i : ι) :
    sigmaAlgExcept (X := X) i = (⊥ : MeasurableSpace (∀ j, X j)) := by
  have hcomp : ({i}ᶜ : Set ι) = ∅ := by
    ext j
    simp [Subsingleton.elim j i]
  simp [sigmaAlgExcept, hcomp]

/-- Conditional expectation of `f` given all coordinates except `i`. -/
def condExpExceptCoord (i : ι) (f : (∀ j, X j) → ℝ) :
    (∀ j, X j) → ℝ :=
  (Measure.pi μ)[f | sigmaAlgExcept i]

lemma efron_stein_isEmpty [IsEmpty ι]
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (_hf : MemLp f 2 (Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] := by
  simp [variance_pi_of_isEmpty μ f]

/-! ## Efron-Stein proved declarations -/

theorem efron_stein_of_integral_bound
    (f : (∀ j, X j) → ℝ)
    (hES :
      Var[f; Measure.pi μ] ≤
        ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by
  exact hES

lemma efron_stein_term_eq_integral_condVar_exceptCoord
    [∀ i, IsProbabilityMeasure (μ i)]
    (i : ι) (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) =
      (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] := by
  classical
  have hm : sigmaAlgExcept i ≤ (inferInstance : MeasurableSpace (∀ j, X j)) :=
    sigmaAlgExcept_le (X := X) i
  have hfi : Integrable (fun ω => (f ω - condExpExceptCoord μ i f ω) ^ 2) (Measure.pi μ) := by
    exact (hf.sub hf.condExp).integrable_sq
  calc
    ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ)
        = ∫ ω in Set.univ, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by simp
    _ = ∫ ω in Set.univ, (Var[f; Measure.pi μ | sigmaAlgExcept i]) ω ∂(Measure.pi μ) := by
      symm
      exact setIntegral_condVar (m := sigmaAlgExcept i) (hm := hm)
        (μ := Measure.pi μ) (X := f) (s := Set.univ) hfi (by simp)
    _ = (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] := by simp

lemma efron_stein_rhs_eq_sum_integral_condVar
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    (∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ))
      =
    (∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]]) := by
  classical
  refine Finset.sum_congr rfl ?_
  intro i hi
  simpa using efron_stein_term_eq_integral_condVar_exceptCoord (μ := μ) i f hf

theorem efron_stein_of_condVar_sum_bound
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ))
    (hCondVar :
      Var[f; Measure.pi μ] ≤
        ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]]) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by
  have hEq :=
    efron_stein_rhs_eq_sum_integral_condVar (μ := μ) f hf
  calc
    Var[f; Measure.pi μ]
      ≤ ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] := hCondVar
    _ = ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by
      simpa [eq_comm] using hEq

theorem efron_stein_to_condVar_sum_bound
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ))
    (hES :
      Var[f; Measure.pi μ] ≤
        ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] := by
  simpa [efron_stein_rhs_eq_sum_integral_condVar (μ := μ) f hf] using hES

theorem efron_stein_iff_condVar_sum_bound
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    (Var[f; Measure.pi μ] ≤
        ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ))
      ↔
    (Var[f; Measure.pi μ] ≤
        ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]]) := by
  constructor
  · intro hES
    exact efron_stein_to_condVar_sum_bound (μ := μ) f hf hES
  · intro hCondVar
    exact efron_stein_of_condVar_sum_bound (μ := μ) f hf hCondVar

lemma efron_stein_rhs_nonneg
    (f : (∀ j, X j) → ℝ) :
    0 ≤ ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by
  classical
  refine Finset.sum_nonneg ?_
  intro i hi
  exact integral_nonneg (fun _ => sq_nonneg _)

theorem efron_stein_unique_eq
    [Unique ι]
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    Var[f; Measure.pi μ] =
      ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by
  classical
  have hsig : sigmaAlgExcept (default : ι) = (⊥ : MeasurableSpace (∀ j, X j)) :=
    sigmaAlgExcept_eq_bot (X := X) (default : ι)
  have hterm :
      ∫ ω, (f ω - condExpExceptCoord μ (default : ι) f ω) ^ 2 ∂(Measure.pi μ) =
        Var[f; Measure.pi μ] := by
    calc
      ∫ ω, (f ω - condExpExceptCoord μ (default : ι) f ω) ^ 2 ∂(Measure.pi μ)
          = (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept (default : ι)]] :=
        efron_stein_term_eq_integral_condVar_exceptCoord (μ := μ) (default : ι) f hf
      _ = (Measure.pi μ)[Var[f; Measure.pi μ | (⊥ : MeasurableSpace (∀ j, X j))]] := by
        simp [hsig]
      _ = ∫ ω, (Var[f; Measure.pi μ | (⊥ : MeasurableSpace (∀ j, X j))]) ω ∂(Measure.pi μ) := by
        rfl
      _ = ∫ ω, Var[f; Measure.pi μ] ∂(Measure.pi μ) := by
        simp [condVar_bot (μ := Measure.pi μ) (hX := hf.aemeasurable)]
      _ = Var[f; Measure.pi μ] := by simp
  have hsum :
      (∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ)) =
      ∫ ω, (f ω - condExpExceptCoord μ (default : ι) f ω) ^ 2 ∂(Measure.pi μ) := by
    exact (Fintype.sum_unique (f := fun i : ι =>
      ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ)))
  rw [hsum, hterm]

theorem efron_stein_unique
    [Unique ι]
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) := by
  exact (efron_stein_unique_eq (μ := μ) f hf).le

lemma efron_stein_core_unique [Unique ι]
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] :=
  (efron_stein_iff_condVar_sum_bound (μ := μ) f hf).mp (efron_stein_unique (μ := μ) f hf)

/-! ## Sorry-bearing declarations -/

/-! ### Commutativity of conditional expectations on product spaces

On `Measure.pi μ` with independent coordinates, conditional expectations
`E[·|sigmaAlgExcept i₀]` and `E[·|sigmaAlgExcept j]` commute for `j ≠ i₀`.

**Proof strategy**: Dynkin π-λ theorem. Define a π-system
  `piSys i₀ j = {A ∩ B ∩ C : A ∈ σ_{ij}, B ∈ σ_{i₀}, C ∈ σ_j}`
that generates `MeasurableSpace.pi`. Show `d = LHS - RHS` has `∫_s d = 0` for
all rectangles `s ∈ piSys` using independence (`condExp_indep_eq`) +
`setIntegral_condExp`. Then `induction_on_inter` extends to all measurable sets,
and `ae_eq_of_forall_setIntegral_eq` gives `d =ᵃᵉ 0`.
-/

-- Infrastructure for Dynkin π-λ proof of condExp commutativity

/-- σ-algebra generated by a single coordinate k. -/
private abbrev σ_coord (k : ι) : MeasurableSpace (∀ i, X i) :=
  MeasurableSpace.comap (fun x : ∀ i, X i => x k) (‹∀ i, MeasurableSpace (X i)› k)

set_option linter.unusedSectionVars false in
private lemma σ_coord_le_pi [DecidableEq ι] (k : ι) :
    σ_coord (X := X) k ≤ (MeasurableSpace.pi : MeasurableSpace (∀ j, X j)) :=
  le_iSup (fun a : ι =>
    MeasurableSpace.comap (fun x : (∀ b, X b) => x a)
      (inferInstance : MeasurableSpace (X a))) k

set_option linter.unusedSectionVars false in
private lemma σ_coord_le_except [DecidableEq ι] (k j : ι) (hkj : k ≠ j) :
    σ_coord (X := X) k ≤ sigmaAlgExcept (X := X) j :=
  le_iSup₂_of_le k (by simp [hkj]) le_rfl

set_option linter.unusedSectionVars false in
private lemma σ_coord_le_inf [DecidableEq ι] (k i₀ j : ι) (hki : k ≠ i₀) (hkj : k ≠ j) :
    σ_coord (X := X) k ≤ sigmaAlgExcept (X := X) i₀ ⊓ sigmaAlgExcept (X := X) j :=
  le_inf (σ_coord_le_except (X := X) k i₀ hki) (σ_coord_le_except (X := X) k j hkj)

/-- π-system for Dynkin extension: rectangles from σ_{ij} × σ_{i₀} × σ_j. -/
private def piSys [DecidableEq ι] (i₀ j : ι) : Set (Set (∀ k, X k)) :=
  {s | ∃ (A B C : Set (∀ k, X k)),
    @MeasurableSet _ (sigmaAlgExcept (X := X) i₀ ⊓ sigmaAlgExcept (X := X) j) A ∧
    @MeasurableSet _ (σ_coord (X := X) i₀) B ∧
    @MeasurableSet _ (σ_coord (X := X) j) C ∧
    s = A ∩ B ∩ C}

set_option linter.unusedSectionVars false in
private lemma isPiSystem_piSys [DecidableEq ι] (i₀ j : ι) :
    IsPiSystem (piSys (X := X) i₀ j) := by
  intro s₁ hs₁ s₂ hs₂ _hne
  obtain ⟨A₁, B₁, C₁, hA₁, hB₁, hC₁, rfl⟩ := hs₁
  obtain ⟨A₂, B₂, C₂, hA₂, hB₂, hC₂, rfl⟩ := hs₂
  refine ⟨A₁ ∩ A₂, B₁ ∩ B₂, C₁ ∩ C₂, hA₁.inter hA₂, hB₁.inter hB₂, hC₁.inter hC₂, ?_⟩
  ext x; simp [Set.mem_inter_iff]; tauto

set_option linter.unusedSectionVars false in
private lemma generateFrom_piSys [DecidableEq ι] (i₀ j : ι) (hij : j ≠ i₀) :
    MeasurableSpace.pi = MeasurableSpace.generateFrom (piSys (X := X) i₀ j) := by
  apply le_antisymm
  · rw [show (MeasurableSpace.pi : MeasurableSpace (∀ k, X k)) =
      ⨆ k, σ_coord (X := X) k from rfl]
    refine iSup_le ?_
    intro k s hs
    apply MeasurableSpace.measurableSet_generateFrom
    by_cases hki : k = i₀
    · subst hki
      exact ⟨Set.univ, s, Set.univ, MeasurableSet.univ, hs, MeasurableSet.univ, by simp⟩
    · by_cases hkj : k = j
      · subst hkj
        exact ⟨Set.univ, Set.univ, s, MeasurableSet.univ, MeasurableSet.univ, hs, by simp⟩
      · exact ⟨s, Set.univ, Set.univ,
          σ_coord_le_inf (X := X) k i₀ j hki hkj s hs,
          MeasurableSet.univ, MeasurableSet.univ, by simp⟩
  · refine generateFrom_le ?_
    intro s hs
    obtain ⟨A, B, C, hA, hB, hC, rfl⟩ := hs
    exact ((le_trans inf_le_left (sigmaAlgExcept_le i₀)) A hA |>.inter
      (σ_coord_le_pi (X := X) i₀ B hB)).inter (σ_coord_le_pi (X := X) j C hC)

set_option linter.unusedSectionVars false in
/-- Coordinate σ-algebras are iIndep on the product space. -/
private lemma iIndep_coord_pi [DecidableEq ι] [∀ i, IsProbabilityMeasure (μ i)] :
    iIndep (σ_coord (X := X)) (μ := Measure.pi μ) :=
  (@iIndepFun_pi ι _ X _ μ _ X _ (fun i => @id (X i)) (fun i => aemeasurable_id)).iIndep

set_option linter.unusedSectionVars false in
private lemma indep_sigmaAlgExcept_coord [DecidableEq ι]
    [∀ i, IsProbabilityMeasure (μ i)] (i₀ : ι) :
    Indep (sigmaAlgExcept (X := X) i₀) (σ_coord (X := X) i₀) (μ := Measure.pi μ) := by
  have hindep := iIndep_coord_pi (X := X) μ
  have hdisjoint : Disjoint ({i₀}ᶜ : Set ι) ({i₀} : Set ι) := by simp [Set.disjoint_iff]
  have h := indep_iSup_of_disjoint (σ_coord_le_pi (X := X)) hindep hdisjoint
  convert h using 1
  simp only [Set.mem_singleton_iff, iSup_iSup_eq_left]

set_option linter.unusedSectionVars false in
/-- Dynkin π-λ extension: if d is integrable with zero integral and zero set-integral
on all elements of the π-system, then d =ᵃᵉ 0. -/
private lemma ae_eq_zero_of_integral_piSys_zero [DecidableEq ι]
    [∀ i, IsProbabilityMeasure (μ i)]
    (d : (∀ j, X j) → ℝ) (hd_int : Integrable d (Measure.pi μ))
    (hd_zero : ∫ x, d x ∂(Measure.pi μ) = 0)
    (i₀ j : ι) (hij : j ≠ i₀)
    (h_piSys : ∀ s ∈ piSys (X := X) i₀ j, ∫ x in s, d x ∂(Measure.pi μ) = 0) :
    d =ᵐ[Measure.pi μ] 0 := by
  rw [show (0 : (∀ j, X j) → ℝ) = fun _ => (0 : ℝ) from rfl]
  refine Integrable.ae_eq_of_forall_setIntegral_eq d (fun _ => 0)
    hd_int (integrable_const 0) (fun s hs _hμs => ?_)
  simp only [integral_const, smul_eq_mul, mul_zero]
  refine @MeasurableSpace.induction_on_inter _ _
    (fun s _ => ∫ x in s, d x ∂(Measure.pi μ) = 0)
    (piSys (X := X) i₀ j)
    (generateFrom_piSys (X := X) i₀ j hij)
    (isPiSystem_piSys (X := X) i₀ j)
    ?_ ?_ ?_ ?_ s hs
  · simp
  · exact fun t ht => h_piSys t ht
  · intro t ht ht_zero
    rw [setIntegral_compl ht hd_int]; linarith
  · intro g hpwd hgm hg
    rw [integral_iUnion hgm hpwd hd_int.integrableOn]; simp [hg]

set_option linter.unusedSectionVars false in
/-- For f that is m₁-StronglyMeasurable with m₁ ⊥ m₂, and B ∈ m₂:
∫_B f = (∫ f) * P.real B. Uses `condExp_indep_eq` + `setIntegral_condExp`. -/
private lemma setIntegral_eq_integral_mul_meas_of_indep [DecidableEq ι]
    [∀ i, IsProbabilityMeasure (μ i)]
    {m₁ m₂ : MeasurableSpace (∀ j, X j)}
    (hle₁ : m₁ ≤ MeasurableSpace.pi) (hle₂ : m₂ ≤ MeasurableSpace.pi)
    (hindep : Indep m₁ m₂ (μ := Measure.pi μ))
    {f : (∀ j, X j) → ℝ}
    (hf_int : Integrable f (Measure.pi μ))
    (hf_sm : @StronglyMeasurable (∀ j, X j) ℝ _ m₁ f)
    {B : Set (∀ j, X j)} (hB : @MeasurableSet _ m₂ B) :
    ∫ x in B, f x ∂(Measure.pi μ) =
      (∫ x, f x ∂(Measure.pi μ)) * (Measure.pi μ).real B := by
  haveI : SigmaFinite ((Measure.pi μ).trim hle₂) := by
    have : IsFiniteMeasure ((Measure.pi μ).trim hle₂) := by
      constructor; rw [trim_measurableSet_eq hle₂ MeasurableSet.univ]; exact measure_lt_top _ _
    exact this.toSigmaFinite
  have hcondExp_const : (Measure.pi μ)[f|m₂] =ᵐ[Measure.pi μ] fun _ => ∫ x, f x ∂(Measure.pi μ) :=
    condExp_indep_eq hle₁ hle₂ hf_sm hindep
  have hsetInt := setIntegral_condExp hle₂ hf_int hB
  rw [← hsetInt]
  rw [setIntegral_congr_ae (hle₂ B hB) (hcondExp_const.mono (fun x hx _hxB => hx))]
  simp [integral_const, Measure.real]; ring

set_option linter.unusedSectionVars false in
private lemma condExp_condExp_comm_pi
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ) (hf : Integrable f (Measure.pi μ))
    (i₀ j : ι) (hij : j ≠ i₀) :
    (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept i₀] | sigmaAlgExcept j] =ᵐ[Measure.pi μ]
      (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept j] | sigmaAlgExcept i₀] := by
  classical
  -- M = sigmaAlgExcept j, N = sigmaAlgExcept i₀
  -- LHS = P[P[f|N]|M], RHS = P[P[f|M]|N], d = LHS - RHS
  have hM : sigmaAlgExcept (X := X) j ≤ MeasurableSpace.pi := sigmaAlgExcept_le (X := X) j
  have hN : sigmaAlgExcept (X := X) i₀ ≤ MeasurableSpace.pi := sigmaAlgExcept_le (X := X) i₀
  -- Integrability (use integrable_condExp which is unconditional)
  have hfN_int : Integrable ((Measure.pi μ)[f | sigmaAlgExcept i₀]) (Measure.pi μ) :=
    integrable_condExp
  have hfM_int : Integrable ((Measure.pi μ)[f | sigmaAlgExcept j]) (Measure.pi μ) :=
    integrable_condExp
  have hLHS_int : Integrable
      ((Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept i₀] | sigmaAlgExcept j])
      (Measure.pi μ) := integrable_condExp
  have hRHS_int : Integrable
      ((Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept j] | sigmaAlgExcept i₀])
      (Measure.pi μ) := integrable_condExp
  -- d is integrable
  have hd_int : Integrable
      (fun ω => (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept i₀] | sigmaAlgExcept j] ω -
        (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept j] | sigmaAlgExcept i₀] ω)
      (Measure.pi μ) := hLHS_int.sub hRHS_int
  -- ∫ d = 0: both sides have integral E[f] by tower property
  have hd_zero : ∫ x,
      ((Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept i₀] | sigmaAlgExcept j] x -
       (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept j] | sigmaAlgExcept i₀] x)
      ∂(Measure.pi μ) = 0 := by
    rw [integral_sub hLHS_int hRHS_int]
    have h1 : ∫ x, (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept i₀] | sigmaAlgExcept j] x
        ∂(Measure.pi μ) = ∫ x, f x ∂(Measure.pi μ) := by
      rw [integral_condExp hM, integral_condExp hN]
    have h2 : ∫ x, (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept j] | sigmaAlgExcept i₀] x
        ∂(Measure.pi μ) = ∫ x, f x ∂(Measure.pi μ) := by
      rw [integral_condExp hN, integral_condExp hM]
    rw [h1, h2, sub_self]
  -- Rectangle computation: ∫_{A∩B∩C} d = 0 for rectangles in piSys
  have h_piSys : ∀ s ∈ piSys (X := X) i₀ j,
      ∫ x in s,
        ((Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept i₀] | sigmaAlgExcept j] x -
         (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept j] | sigmaAlgExcept i₀] x)
        ∂(Measure.pi μ) = 0 := by
    intro s hs
    obtain ⟨A, B, C, hA, hB, hC, rfl⟩ := hs
    -- Measurability transfers
    have hA_N : @MeasurableSet _ (sigmaAlgExcept (X := X) i₀) A :=
      (inf_le_left (a := sigmaAlgExcept (X := X) i₀)
                   (b := sigmaAlgExcept (X := X) j)) A hA
    have hA_M : @MeasurableSet _ (sigmaAlgExcept (X := X) j) A :=
      (inf_le_right (a := sigmaAlgExcept (X := X) i₀)
                    (b := sigmaAlgExcept (X := X) j)) A hA
    have hB_M : @MeasurableSet _ (sigmaAlgExcept (X := X) j) B :=
      σ_coord_le_except (X := X) i₀ j hij.symm B hB
    have hC_N : @MeasurableSet _ (sigmaAlgExcept (X := X) i₀) C :=
      σ_coord_le_except (X := X) j i₀ hij C hC
    have hAB_M : @MeasurableSet _ (sigmaAlgExcept (X := X) j) (A ∩ B) := hA_M.inter hB_M
    have hAC_N : @MeasurableSet _ (sigmaAlgExcept (X := X) i₀) (A ∩ C) := hA_N.inter hC_N
    -- Independence of coordinate σ-algebras
    have hM_indep_j : Indep (sigmaAlgExcept (X := X) j) (σ_coord (X := X) j)
        (μ := Measure.pi μ) := indep_sigmaAlgExcept_coord μ j
    have hN_indep_i : Indep (sigmaAlgExcept (X := X) i₀) (σ_coord (X := X) i₀)
        (μ := Measure.pi μ) := indep_sigmaAlgExcept_coord μ i₀
    -- SigmaFinite for trimmed measures
    haveI : SigmaFinite ((Measure.pi μ).trim hM) := by
      have : IsFiniteMeasure ((Measure.pi μ).trim hM) := by
        constructor; rw [trim_measurableSet_eq hM MeasurableSet.univ]; exact measure_lt_top _ _
      exact this.toSigmaFinite
    haveI : SigmaFinite ((Measure.pi μ).trim hN) := by
      have : IsFiniteMeasure ((Measure.pi μ).trim hN) := by
        constructor; rw [trim_measurableSet_eq hN MeasurableSet.univ]; exact measure_lt_top _ _
      exact this.toSigmaFinite
    -- ∫_{A∩B∩C} LHS = P.real(C) * P.real(B) * ∫_A f
    -- Chain: factor C via M⊥σ_j → condExp on A∩B∈M → factor B via N⊥σ_{i₀} → condExp on A∈N
    have hLHS_final : ∫ x in A ∩ B ∩ C,
        (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept i₀] | sigmaAlgExcept j] x
        ∂(Measure.pi μ) =
        (Measure.pi μ).real C * (Measure.pi μ).real B * ∫ x in A, f x ∂(Measure.pi μ) := by
      have h1 : ∫ x in A ∩ B ∩ C,
          (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept i₀] | sigmaAlgExcept j] x
          ∂(Measure.pi μ) =
          (∫ x in A ∩ B,
            (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept i₀] | sigmaAlgExcept j] x
            ∂(Measure.pi μ)) * (Measure.pi μ).real C := by
        rw [show A ∩ B ∩ C = C ∩ (A ∩ B) from by ext x; simp [Set.mem_inter_iff]; tauto]
        rw [← setIntegral_indicator (hM (A ∩ B) hAB_M)]
        rw [setIntegral_eq_integral_mul_meas_of_indep μ hM
          (σ_coord_le_pi (X := X) j) hM_indep_j
          (hLHS_int.indicator (hM (A ∩ B) hAB_M))
          (stronglyMeasurable_condExp.indicator hAB_M) hC]
        rw [integral_indicator (hM (A ∩ B) hAB_M)]
      have h2 : ∫ x in A ∩ B,
          (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept i₀] | sigmaAlgExcept j] x
          ∂(Measure.pi μ) =
          ∫ x in A ∩ B, (Measure.pi μ)[f | sigmaAlgExcept i₀] x ∂(Measure.pi μ) :=
        setIntegral_condExp hM hfN_int hAB_M
      have h3 : ∫ x in A ∩ B,
          (Measure.pi μ)[f | sigmaAlgExcept i₀] x ∂(Measure.pi μ) =
          (∫ x in A, (Measure.pi μ)[f | sigmaAlgExcept i₀] x ∂(Measure.pi μ)) *
            (Measure.pi μ).real B := by
        rw [Set.inter_comm A B, ← setIntegral_indicator (hN A hA_N)]
        rw [setIntegral_eq_integral_mul_meas_of_indep μ hN
          (σ_coord_le_pi (X := X) i₀) hN_indep_i
          (hfN_int.indicator (hN A hA_N))
          (stronglyMeasurable_condExp.indicator hA_N) hB]
        rw [integral_indicator (hN A hA_N)]
      have h4 : ∫ x in A, (Measure.pi μ)[f | sigmaAlgExcept i₀] x ∂(Measure.pi μ) =
          ∫ x in A, f x ∂(Measure.pi μ) :=
        setIntegral_condExp hN hf hA_N
      rw [h1, h2, h3, h4]; ring
    -- ∫_{A∩B∩C} RHS = P.real(C) * P.real(B) * ∫_A f  (symmetric chain)
    -- Chain: factor B via N⊥σ_{i₀} → condExp on A∩C∈N → factor C via M⊥σ_j → condExp on A∈M
    have hRHS_final : ∫ x in A ∩ B ∩ C,
        (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept j] | sigmaAlgExcept i₀] x
        ∂(Measure.pi μ) =
        (Measure.pi μ).real C * (Measure.pi μ).real B * ∫ x in A, f x ∂(Measure.pi μ) := by
      have h1 : ∫ x in A ∩ B ∩ C,
          (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept j] | sigmaAlgExcept i₀] x
          ∂(Measure.pi μ) =
          (∫ x in A ∩ C,
            (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept j] | sigmaAlgExcept i₀] x
            ∂(Measure.pi μ)) * (Measure.pi μ).real B := by
        rw [show A ∩ B ∩ C = B ∩ (A ∩ C) from by ext x; simp [Set.mem_inter_iff]; tauto]
        rw [← setIntegral_indicator (hN (A ∩ C) hAC_N)]
        rw [setIntegral_eq_integral_mul_meas_of_indep μ hN
          (σ_coord_le_pi (X := X) i₀) hN_indep_i
          (hRHS_int.indicator (hN (A ∩ C) hAC_N))
          (stronglyMeasurable_condExp.indicator hAC_N) hB]
        rw [integral_indicator (hN (A ∩ C) hAC_N)]
      have h2 : ∫ x in A ∩ C,
          (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept j] | sigmaAlgExcept i₀] x
          ∂(Measure.pi μ) =
          ∫ x in A ∩ C, (Measure.pi μ)[f | sigmaAlgExcept j] x ∂(Measure.pi μ) :=
        setIntegral_condExp hN hfM_int hAC_N
      have h3 : ∫ x in A ∩ C,
          (Measure.pi μ)[f | sigmaAlgExcept j] x ∂(Measure.pi μ) =
          (∫ x in A, (Measure.pi μ)[f | sigmaAlgExcept j] x ∂(Measure.pi μ)) *
            (Measure.pi μ).real C := by
        rw [Set.inter_comm A C, ← setIntegral_indicator (hM A hA_M)]
        rw [setIntegral_eq_integral_mul_meas_of_indep μ hM
          (σ_coord_le_pi (X := X) j) hM_indep_j
          (hfM_int.indicator (hM A hA_M))
          (stronglyMeasurable_condExp.indicator hA_M) hC]
        rw [integral_indicator (hM A hA_M)]
      have h4 : ∫ x in A, (Measure.pi μ)[f | sigmaAlgExcept j] x ∂(Measure.pi μ) =
          ∫ x in A, f x ∂(Measure.pi μ) :=
        setIntegral_condExp hM hf hA_M
      rw [h1, h2, h3, h4]; ring
    -- ∫_s d = ∫_s LHS - ∫_s RHS = 0
    rw [integral_sub hLHS_int.integrableOn hRHS_int.integrableOn]
    rw [hLHS_final, hRHS_final, sub_self]
  -- Apply Dynkin π-λ extension: d =ᵃᵉ 0
  have hd_ae_zero :
      (fun ω => (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept i₀] | sigmaAlgExcept j] ω -
        (Measure.pi μ)[(Measure.pi μ)[f | sigmaAlgExcept j] | sigmaAlgExcept i₀] ω)
      =ᵐ[Measure.pi μ] 0 :=
    ae_eq_zero_of_integral_piSys_zero μ _ hd_int hd_zero i₀ j hij h_piSys
  -- d =ᵃᵉ 0 implies LHS =ᵃᵉ RHS
  filter_upwards [hd_ae_zero] with x hx
  simp only [Pi.zero_apply] at hx
  linarith

/-! ### Variance contraction under conditional expectation

For `g = E[f | sigmaAlgExcept i₀]` and `j ≠ i₀`:
  `∫ Var[g | σ(j)] ≤ ∫ Var[f | σ(j)]`

**Proof** (using 4 applications of LTV + commutativity + L² contraction):
Let M = sigmaAlgExcept j, N = sigmaAlgExcept i₀, g = E[f|N], h = f - g.

1. LTV gives: ∫ Var[g|M] = Var[g] - Var[E[g|M]]
2. LTV gives: ∫ Var[f|M] = Var[f] - Var[E[f|M]]
3. LTV gives: Var[g] = Var[f] - ∫ Var[f|N]
4. Commutativity: E[g|M] =ᵃᵉ E[E[f|M]|N]
5. LTV gives: Var[E[f|M]] = ∫ Var[E[f|M]|N] + Var[E[E[f|M]|N]]
6. From (4)+(5): Var[E[f|M]] - Var[E[g|M]] = ∫ Var[E[f|M]|N]
7. Substituting (3)+(6) into (1)-(2):
   ∫ Var[g|M] - ∫ Var[f|M] = ∫ Var[E[f|M]|N] - ∫ Var[f|N]
8. Key claim: ∫ Var[E[f|M]|N] ≤ ∫ Var[f|N]
   Proof: With commutativity, ∫ Var[E[f|M]|N] = ∫ (E[h|M])²
          and ∫ Var[f|N] = ∫ h², where h = f - E[f|N].
          Then ∫ (E[h|M])² ≤ ∫ h² by L² contraction of conditional expectation.
-/

/-- Conditional expectation is an L² contraction: `∫ (E[h|m])² ≤ ∫ h²`.
This follows from `Var[E[h|m]] ≤ Var[h]` (law of total variance) and `E[E[h|m]] = E[h]`. -/
private lemma integral_sq_condExp_le
    [∀ i, IsProbabilityMeasure (μ i)]
    (h : (∀ j, X j) → ℝ) (hh : MemLp h 2 (Measure.pi μ))
    (m : MeasurableSpace (∀ j, X j)) (hm : m ≤ (MeasurableSpace.pi : MeasurableSpace (∀ j, X j))) :
    ∫ ω, ((Measure.pi μ)[h | m] ω) ^ 2 ∂(Measure.pi μ) ≤
      ∫ ω, h ω ^ 2 ∂(Measure.pi μ) := by
  have hh_int := hh.integrable (by norm_num)
  have hPh : MemLp ((Measure.pi μ)[h | m]) 2 (Measure.pi μ) := hh.condExp
  -- Var[E[h|m]] ≤ Var[h] from LTV
  have hvar_le : Var[(Measure.pi μ)[h | m]; Measure.pi μ] ≤ Var[h; Measure.pi μ] := by
    have hltv := integral_condVar_add_variance_condExp hm (μ := Measure.pi μ) hh
    have hnn : 0 ≤ ∫ ω, (Var[h; Measure.pi μ | m]) ω ∂(Measure.pi μ) := by
      exact integral_nonneg_of_ae (condExp_nonneg (ae_of_all _ fun ω => sq_nonneg _))
    linarith
  -- ∫ (E[h|m])² = Var[E[h|m]] + (E[h])² by variance_eq_sub
  have hPh_sq : ∫ ω, ((Measure.pi μ)[h | m] ω) ^ 2 ∂(Measure.pi μ) =
      Var[(Measure.pi μ)[h | m]; Measure.pi μ] +
        (∫ ω, (Measure.pi μ)[h | m] ω ∂(Measure.pi μ)) ^ 2 := by
    rw [variance_eq_sub hPh]; simp [Pi.pow_apply]
  -- ∫ h² = Var[h] + (E[h])² by variance_eq_sub
  have hh_sq : ∫ ω, h ω ^ 2 ∂(Measure.pi μ) =
      Var[h; Measure.pi μ] + (∫ ω, h ω ∂(Measure.pi μ)) ^ 2 := by
    rw [variance_eq_sub hh]; simp [Pi.pow_apply]
  -- E[E[h|m]] = E[h] (tower property)
  have hmean_eq : ∫ ω, (Measure.pi μ)[h | m] ω ∂(Measure.pi μ) =
      ∫ ω, h ω ∂(Measure.pi μ) := by
    exact integral_condExp hm
  rw [hPh_sq, hh_sq, hmean_eq]
  linarith

private lemma efron_stein_condVar_le_of_condExp
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ) (hf : MemLp f 2 (Measure.pi μ))
    (i₀ j : ι) (hij : j ≠ i₀) :
    (Measure.pi μ)[Var[condExpExceptCoord μ i₀ f; Measure.pi μ | sigmaAlgExcept j]] ≤
      (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept j]] := by
  classical
  set M := sigmaAlgExcept (X := X) j
  set N := sigmaAlgExcept (X := X) i₀
  set g := condExpExceptCoord μ i₀ f  -- = E[f|N]
  set P := Measure.pi μ
  have hM : M ≤ (MeasurableSpace.pi : MeasurableSpace (∀ j, X j)) := sigmaAlgExcept_le (X := X) j
  have hN : N ≤ (MeasurableSpace.pi : MeasurableSpace (∀ j, X j)) := sigmaAlgExcept_le (X := X) i₀
  have hg : MemLp g 2 P := hf.condExp
  have hfM : MemLp (P[f | M]) 2 P := hf.condExp
  -- LTV: ∫ Var[g|M] + Var[E[g|M]] = Var[g]
  have hltv_gM := integral_condVar_add_variance_condExp hM (μ := P) hg
  -- LTV: ∫ Var[f|M] + Var[E[f|M]] = Var[f]
  have hltv_fM := integral_condVar_add_variance_condExp hM (μ := P) hf
  -- LTV: ∫ Var[f|N] + Var[g] = Var[f]
  have hltv_fN := integral_condVar_add_variance_condExp hN (μ := P) hf
  -- LTV: ∫ Var[E[f|M]|N] + Var[E[E[f|M]|N]] = Var[E[f|M]]
  have hltv_fMN := integral_condVar_add_variance_condExp hN (μ := P) hfM
  -- Commutativity: E[g|M] = E[E[f|N]|M] =ᵃᵉ E[E[f|M]|N]
  have hcomm : P[g | M] =ᵐ[P] P[P[f | M] | N] := by
    exact condExp_condExp_comm_pi μ f (hf.integrable (by norm_num)) i₀ j hij
  -- Var[E[g|M]] = Var[E[E[f|M]|N]] (from commutativity)
  have hvar_comm : Var[P[g | M]; P] = Var[P[P[f | M] | N]; P] :=
    variance_congr hcomm
  -- ∫ Var[f|N] ≥ 0
  have hnn_fN : 0 ≤ P[Var[f; P | N]] := by
    exact integral_nonneg_of_ae (condExp_nonneg (ae_of_all _ fun ω => sq_nonneg _))
  -- ∫ Var[E[f|M]|N] ≥ 0
  have hnn_fMN : 0 ≤ P[Var[P[f | M]; P | N]] := by
    exact integral_nonneg_of_ae (condExp_nonneg (ae_of_all _ fun ω => sq_nonneg _))
  -- Key: from LTV equations, algebraically derive the bound
  -- ∫ Var[g|M] = Var[g] - Var[E[g|M]]
  --            = (Var[f] - ∫ Var[f|N]) - (Var[E[f|M]] - ∫ Var[E[f|M]|N])
  --            = ∫ Var[f|M] + ∫ Var[E[f|M]|N] - ∫ Var[f|N]
  -- So: ∫ Var[g|M] ≤ ∫ Var[f|M] iff ∫ Var[E[f|M]|N] ≤ ∫ Var[f|N]
  -- The latter follows from integral_sq_condExp_le.
  -- But we need to relate ∫ Var[E[f|M]|N] to ∫ (E[h|M])² and ∫ Var[f|N] to ∫ h².
  -- This requires the commutativity step.
  -- For now, we prove the algebraic part and use the nonnegativity bounds.
  -- From equations: ∫ Var[g|M] - ∫ Var[f|M]
  -- = (Var[g] - Var[E[g|M]]) - (Var[f] - Var[E[f|M]])
  -- = -(Var[f] - Var[g]) + (Var[E[f|M]] - Var[E[g|M]])
  -- = -∫ Var[f|N] + (Var[E[f|M]] - Var[E[E[f|M]|N]])     [using hvar_comm]
  -- = -∫ Var[f|N] + ∫ Var[E[f|M]|N]                        [using hltv_fMN]
  -- ≤ 0  iff  ∫ Var[E[f|M]|N] ≤ ∫ Var[f|N]
  -- The latter holds because ∫ Var[X|N] = Var[X] - Var[E[X|N]]
  -- and for X = E[f|M]: Var[E[f|M]] ≤ Var[f] and Var[E[E[f|M]|N]] ≥ 0.
  -- Actually we need a tighter bound. Let's use integral_sq_condExp_le.
  -- Using commutativity: ∫ Var[E[f|M]|N] and ∫ Var[f|N] can be related
  -- to ∫ (E[h|M])² and ∫ h² where h = f - E[f|N].
  -- For now, we use the algebraic bound directly.
  -- ∫ Var[E[f|M]|N] = Var[E[f|M]] - Var[E[E[f|M]|N]]
  --                  = Var[E[f|M]] - Var[E[g|M]]  (commutativity)
  -- ∫ Var[f|N] = Var[f] - Var[g]
  -- Need: Var[E[f|M]] - Var[E[g|M]] ≤ Var[f] - Var[g]
  -- i.e., Var[E[f|M]] - Var[f] ≤ Var[E[g|M]] - Var[g]
  -- i.e., -(Var[f] - Var[E[f|M]]) ≤ -(Var[g] - Var[E[g|M]])
  -- i.e., Var[g] - Var[E[g|M]] ≤ Var[f] - Var[E[f|M]]
  -- i.e., ∫ Var[g|M] ≤ ∫ Var[f|M]  (which is what we want!)
  -- So the algebra is CIRCULAR when expanded this way.
  -- We break the cycle with integral_sq_condExp_le:
  -- ∫ Var[E[f|M]|N] ≤ ∫ Var[f|N] because (with commutativity):
  -- ∫ Var[E[f|M]|N] = ∫ (E[f|M] - E[E[f|M]|N])²
  --                  = ∫ (E[f|M] - E[g|M])²     (comm: E[E[f|M]|N] = E[g|M])
  --                  = ∫ (E[f-g|M])²
  --                  = ∫ (E[h|M])²               (h = f - g)
  -- ∫ Var[f|N] = ∫ (f - E[f|N])² = ∫ h²
  -- And ∫ (E[h|M])² ≤ ∫ h² by integral_sq_condExp_le.
  -- We prove this chain via setIntegral_condVar and integral rewrites.
  -- For the algebraic combination, we use linarith with the 4 LTV equations.
  have h_main : P[Var[P[f | M]; P | N]] ≤ P[Var[f; P | N]] := by
    -- ∫ Var[E[f|M]|N] = Var[E[f|M]] - Var[E[E[f|M]|N]]  (from hltv_fMN)
    -- ∫ Var[f|N] = Var[f] - Var[g]                         (from hltv_fN)
    -- Need: Var[E[f|M]] - Var[E[E[f|M]|N]] ≤ Var[f] - Var[g]
    -- i.e., Var[E[f|M]] + Var[g] ≤ Var[f] + Var[E[E[f|M]|N]]
    -- Using integral_sq_condExp_le on h = f - g w.r.t. M:
    -- ∫ (E[h|M])² ≤ ∫ h²
    -- We need to relate this to the variance terms.
    -- ∫ (E[h|M])² = Var[E[h|M]] + (E[h])²  (variance_eq_sub)
    -- ∫ h² = Var[h] + (E[h])²               (variance_eq_sub)
    -- E[h] = E[f-g] = E[f] - E[g] = E[f] - E[E[f|N]] = E[f] - E[f] = 0
    -- Wait, E[g] = E[E[f|N]] = E[f], so E[h] = E[f-g] = 0.
    -- So: ∫ (E[h|M])² = Var[E[h|M]]
    --     ∫ h² = Var[h]
    -- And: Var[E[h|M]] ≤ Var[h] from integral_sq_condExp_le (or LTV directly)
    -- Now relate to original terms:
    -- h = f - g, E[h|M] = E[f|M] - E[g|M]
    -- Var[h] = Var[f - g]
    -- Var[E[h|M]] = Var[E[f|M] - E[g|M]] = Var[E[f-g|M]]
    -- With commutativity: E[g|M] = E[E[f|N]|M] = E[E[f|M]|N]
    -- So E[f|M] - E[g|M] = E[f|M] - E[E[f|M]|N]
    -- And Var[E[h|M]] = Var[E[f|M] - E[E[f|M]|N]]
    -- But ∫ Var[E[f|M]|N] = ∫ (E[f|M] - E[E[f|M]|N])²  (setIntegral_condVar on Set.univ)
    -- By variance_of_integral_eq_zero (since E[E[f|M] - E[E[f|M]|N]] = 0):
    -- Var[E[f|M] - E[E[f|M]|N]] = ∫ (E[f|M] - E[E[f|M]|N])²
    -- So ∫ Var[E[f|M]|N] = Var[E[f|M] - E[E[f|M]|N]] = Var[E[h|M]]
    -- Similarly: ∫ Var[f|N] = ∫ (f - E[f|N])² = ∫ h²
    -- Since E[h] = 0: ∫ h² = Var[h]
    -- And: Var[E[h|M]] ≤ Var[h] → ∫ Var[E[f|M]|N] ≤ ∫ Var[f|N]
    -- This can be proved using integral_sq_condExp_le on h w.r.t. M.
    set h := f - g with hh_def
    have hh : MemLp h 2 P := hf.sub hg
    have hh_int : Integrable h P := hh.integrable (by norm_num)
    -- h = f - E[f|N], so E[h|M] = E[f-g|M] = E[f|M] - E[g|M]
    -- E[h|M] =ᵃᵉ E[f|M] - E[g|M]
    have hEhM : P[h | M] =ᵐ[P] P[f | M] - P[g | M] :=
      condExp_sub (hf.integrable (by norm_num)) (hg.integrable (by norm_num)) M
    -- Use integral_sq_condExp_le: ∫ (E[h|M])² ≤ ∫ h²
    have h_contraction := integral_sq_condExp_le μ h hh M hM
    -- Step 1: P[Var[f|N]] = ∫ h² via setIntegral_condVar
    have hfi_N : Integrable (fun ω => (f ω - P[f | N] ω) ^ 2) P :=
      (hf.sub hf.condExp).integrable_sq
    have h_rhs : P[Var[f; P | N]] = ∫ ω, (h ω) ^ 2 ∂P := by
      rw [show P[Var[f; P | N]] = ∫ ω in Set.univ, (Var[f; P | N]) ω ∂P from by simp]
      rw [setIntegral_condVar (hm := hN) hfi_N (by simp)]
      simp only [Measure.restrict_univ]
      -- h = f - g = f - P[f|N], so (f ω - P[f|N] ω)² = h ω²
      rfl
    -- Step 2: P[Var[P[f|M]|N]] = ∫ (P[f|M] - P[P[f|M]|N])² via setIntegral_condVar
    have hfMi_N : Integrable (fun ω => (P[f | M] ω - P[P[f | M] | N] ω) ^ 2) P :=
      (hfM.sub hfM.condExp).integrable_sq
    have h_lhs_step1 : P[Var[P[f | M]; P | N]] =
        ∫ ω, (P[f | M] ω - P[P[f | M] | N] ω) ^ 2 ∂P := by
      rw [show P[Var[P[f | M]; P | N]] =
        ∫ ω in Set.univ, (Var[P[f | M]; P | N]) ω ∂P from by simp]
      rw [setIntegral_condVar (hm := hN) hfMi_N (by simp)]
      simp
    -- Step 3: (P[f|M] - P[P[f|M]|N])² =ᵃᵉ (P[h|M])² using commutativity
    -- hcomm : P[g|M] =ᵃᵉ P[P[f|M]|N], so P[P[f|M]|N] =ᵃᵉ P[g|M]
    -- hEhM : P[h|M] =ᵃᵉ P[f|M] - P[g|M]
    -- So P[f|M] - P[P[f|M]|N] =ᵃᵉ P[f|M] - P[g|M] =ᵃᵉ P[h|M]
    have h_ae_eq : (fun ω => (P[f | M] ω - P[P[f | M] | N] ω) ^ 2) =ᵐ[P]
        (fun ω => (P[h | M] ω) ^ 2) := by
      filter_upwards [hcomm.symm, hEhM] with ω hcomm_ω hEhM_ω
      simp only [Pi.sub_apply] at hEhM_ω
      rw [hcomm_ω, hEhM_ω]
    have h_lhs : P[Var[P[f | M]; P | N]] = ∫ ω, (P[h | M] ω) ^ 2 ∂P := by
      rw [h_lhs_step1]
      exact integral_congr_ae h_ae_eq
    -- Combine: P[Var[P[f|M]|N]] = ∫ (P[h|M])² ≤ ∫ h² = P[Var[f|N]]
    rw [h_lhs, h_rhs]
    exact h_contraction
  -- From h_main + LTV equations (algebra verified, see docstring above):
  -- ∫ Var[g|M] = Var[g] - Var[E[g|M]]
  -- ∫ Var[f|M] = Var[f] - Var[E[f|M]]
  -- diff = (Var[g] - Var[f]) + (Var[E[f|M]] - Var[E[g|M]])
  --      = -∫ Var[f|N] + ∫ Var[E[f|M]|N]  (using hvar_comm + hltv_fMN)
  --      ≤ 0  (from h_main)
  -- Normalize hltv_fN: P[f|N] = g definitionally (g = condExpExceptCoord μ i₀ f = P[f|N])
  -- linarith cannot see through definitional equality, so we rewrite explicitly.
  have hgN_eq : P[f | N] = g := rfl
  rw [hgN_eq] at hltv_fN
  -- Now hltv_fN : P[Var[f;P|N]] + Var[g;P] = Var[f;P]
  -- The algebra:
  -- P[Var[g|M]] = Var[g] - Var[E[g|M]]                          (from hltv_gM)
  --            = (Var[f] - P[Var[f|N]]) - Var[E[P[f|M]|N]]      (from hltv_fN, hvar_comm)
  --            = (Var[f] - P[Var[f|N]]) - (Var[P[f|M]] - P[Var[P[f|M]|N]])  (from hltv_fMN)
  -- P[Var[f|M]] = Var[f] - Var[P[f|M]]                          (from hltv_fM)
  -- Difference = P[Var[P[f|M]|N]] - P[Var[f|N]] ≤ 0             (from h_main)
  linarith [hltv_gM, hltv_fM, hltv_fN, hltv_fMN, hvar_comm, h_main]

private theorem efron_stein_core_gen (n : ℕ) :
    ∀ {ι : Type*} [Fintype ι]
      {X : ι → Type*} [∀ i, MeasurableSpace (X i)]
      (μ : ∀ i, Measure (X i)) [∀ i, IsProbabilityMeasure (μ i)]
      (f : (∀ j, X j) → ℝ),
      Fintype.card ι = n →
      MemLp f 2 (Measure.pi μ) →
      Var[f; Measure.pi μ] ≤
        ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] := by
  induction n with
  | zero =>
    intro ι _ X _ μ _ f hn hf
    haveI : IsEmpty ι := Fintype.card_eq_zero_iff.mp hn
    simp [variance_pi_of_isEmpty μ f]
  | succ n ih =>
    intro ι _ X _ μ _ f hn hf
    classical
    have hpos : 0 < Fintype.card ι := hn ▸ Nat.succ_pos n
    obtain ⟨i₀⟩ : Nonempty ι := Fintype.card_pos_iff.mp hpos
    set g := condExpExceptCoord μ i₀ f with hg_def
    have hg : MemLp g 2 (Measure.pi μ) := hf.condExp
    have hltv : (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i₀]] +
        Var[g; Measure.pi μ] = Var[f; Measure.pi μ] :=
      integral_condVar_add_variance_condExp (sigmaAlgExcept_le (X := X) i₀)
        (μ := Measure.pi μ) hf
    have hcondExp_g : (Measure.pi μ)[g | sigmaAlgExcept i₀] = g :=
      condExp_of_stronglyMeasurable (sigmaAlgExcept_le (X := X) i₀)
        stronglyMeasurable_condExp (hg.integrable (by norm_num))
    have hltv_g : (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept i₀]] = 0 := by
      have hltv2 := integral_condVar_add_variance_condExp (sigmaAlgExcept_le (X := X) i₀)
        (μ := Measure.pi μ) hg
      simp only [hcondExp_g] at hltv2
      linarith [variance_nonneg g (Measure.pi μ)]
    have hsum_f :
        ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] =
        (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i₀]] +
        ∑ j ∈ Finset.univ.erase i₀,
          (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept j]] :=
      (Finset.sum_erase_add Finset.univ _ (Finset.mem_univ i₀)).symm.trans (add_comm _ _)
    -- Efron-Stein for g: Var[g] ≤ ∑ j, E[Var[g|σ_j]]
    -- g is (sigmaAlgExcept i₀)-measurable, so effectively depends on n coordinates.
    -- We use E-S for g on the same space, then split and bound.
    have hg_es : Var[g; Measure.pi μ] ≤
        ∑ j : ι, (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] := by
      -- Dimension reduction: g = E[f|σ_{-i₀}] is σ_{-i₀}-measurable,
      -- so by Doob-Dynkin it factors through the restriction map.
      -- We apply IH to the factored function g̃ on the reduced index set {j ≠ i₀}.
      set restrict := (fun x (j : {j : ι // j ≠ i₀}) => x j.val :
        (∀ j, X j) → ∀ j : {j : ι // j ≠ i₀}, X j.val) with hrestrict_def
      -- Step 1: sigmaAlgExcept i₀ ≤ comap restrict MeasurableSpace.pi
      have hle_comap : sigmaAlgExcept (X := X) i₀ ≤
          MeasurableSpace.comap restrict MeasurableSpace.pi := by
        apply iSup₂_le
        intro j hj
        rw [Set.mem_compl_iff, Set.mem_singleton_iff] at hj
        have : (fun (x : ∀ k, X k) => x j) =
          (fun (y : ∀ k : {k : ι // k ≠ i₀}, X k.val) => y ⟨j, hj⟩) ∘ restrict := rfl
        rw [this, ← MeasurableSpace.comap_comp]
        exact MeasurableSpace.comap_mono (le_iSup (fun (k : {k : ι // k ≠ i₀}) =>
          MeasurableSpace.comap (fun (y : ∀ k : {k : ι // k ≠ i₀}, X k.val) => y k)
            (inferInstance : MeasurableSpace (X k.val))) ⟨j, hj⟩)
      -- Step 2: Factor g = g̃ ∘ restrict (Doob-Dynkin lemma)
      have hg_sm : StronglyMeasurable[sigmaAlgExcept (X := X) i₀] g :=
        stronglyMeasurable_condExp
      obtain ⟨gtil, hgtil_sm, hg_factor⟩ :=
        (hg_sm.mono hle_comap).exists_eq_measurable_comp
      -- Step 3: Marginal measure (π μ).map restrict = π μ'
      set μ' := (fun j : {j : ι // j ≠ i₀} => μ j.val)
      have hf_meas : Measurable restrict :=
        measurable_pi_lambda _ (fun j => measurable_pi_apply j.val)
      have hpi_map : (Measure.pi μ).map restrict = Measure.pi μ' := by
        have hmp := measurePreserving_piEquivPiSubtypeProd μ (· ≠ i₀)
        have hrest : restrict =
          Prod.fst ∘ (MeasurableEquiv.piEquivPiSubtypeProd X (· ≠ i₀)) := by
          ext x j; rfl
        rw [hrest, ← Measure.map_map measurable_fst
          (MeasurableEquiv.piEquivPiSubtypeProd X (· ≠ i₀)).measurable,
          hmp.map_eq]
        exact Measure.fst_prod
      -- Step 4: Variance transfer Var[g; π μ] = Var[g̃; π μ']
      have hvar_eq : Var[g; Measure.pi μ] = Var[gtil; Measure.pi μ'] := by
        rw [hg_factor,
          ← variance_map hgtil_sm.aemeasurable hf_meas.aemeasurable,
          hpi_map]
      -- Step 5: MemLp transfer
      have hgtil_memlp : MemLp gtil 2 (Measure.pi μ') := by
        rw [← hpi_map,
          memLp_map_measure_iff hgtil_sm.aestronglyMeasurable hf_meas.aemeasurable]
        rw [← hg_factor]; exact hg
      -- Step 6: Cardinality
      have hcard : Fintype.card {j : ι // j ≠ i₀} = n := by
        rw [Fintype.card_subtype_compl, Fintype.card_subtype_eq, hn]; simp
      -- Step 7: Apply IH to g̃ on reduced space
      have hih := ih μ' gtil hcard hgtil_memlp
      -- hih : Var[g̃; π μ'] ≤ ∑_{j'} (π μ')[Var[g̃; π μ' | sigmaAlgExcept j']]
      -- Step 8: Transfer the sum back to the full space
      -- Strategy: For each j ≠ i₀, show P'[Var[g̃|σ'_{-j'}]] = P[Var[g|σ_j]] by:
      -- (a) Commutativity: P[g|M] =ᵃᵉ P[P[f|M]|N], which is N-sm, factors through restrict
      -- (b) ae_eq_condExp: the factored function = P'[g̃|M'] a.e.
      -- (c) variance_map + variance_congr + LTV gives integral equality
      set P := Measure.pi μ with hP_def
      set P' := Measure.pi μ' with hP'_def
      -- Key comap inequality: comap restrict M'_j ≤ N ⊓ M_j (for each j ≠ i₀)
      -- This means: for S ∈ M'_j, restrict⁻¹(S) ∈ N ⊓ M_j
      -- Key measurability facts for restrict w.r.t. sub-σ-algebras
      -- For S ∈ M' (small space), restrict⁻¹'(S) is both N- and M-measurable
      -- Proof: M' generators are eval k' for k' ≠ ⟨j,hj⟩
      --   eval k' ∘ restrict = eval k'.val
      --   k'.val ≠ i₀ (always), k'.val ≠ j (since k' ≠ ⟨j,hj⟩)
      --   So σ_coord k'.val ≤ N ⊓ M

      -- restrict is (N, pi_small)-measurable
      have hrestrict_N_meas : @Measurable _ _ (sigmaAlgExcept (X := X) i₀)
          MeasurableSpace.pi restrict := by
        apply @measurable_pi_lambda _ _ _ (sigmaAlgExcept (X := X) i₀) _
        intro k'
        exact @Measurable.of_comap_le _ _ (sigmaAlgExcept (X := X) i₀) _ (fun x => x k'.val)
          (σ_coord_le_except (X := X) k'.val i₀ k'.property)
      -- restrict is (M, M')-measurable for each j ≠ i₀
      -- We prove comap restrict M' ≤ M via the Galois connection
      have hcomap_M'_le_M : ∀ (j : ι) (hj : j ≠ i₀),
          MeasurableSpace.comap restrict
            (sigmaAlgExcept (X := fun k : {k : ι // k ≠ i₀} => X k.val) ⟨j, hj⟩) ≤
          sigmaAlgExcept (X := X) j := by
        intro j hj
        -- M' = ⨆ k' ∈ {⟨j,hj⟩}ᶜ, comap (eval k') inst
        -- comap restrict M' = ⨆ k' ∈ {⟨j,hj⟩}ᶜ, comap restrict (comap (eval k') inst)
        --                    = ⨆ k' ∈ {⟨j,hj⟩}ᶜ, comap (eval k' ∘ restrict) inst
        --                    = ⨆ k' ∈ {⟨j,hj⟩}ᶜ, comap (eval k'.val) inst
        --                    = ⨆ k' ∈ {⟨j,hj⟩}ᶜ, σ_coord k'.val
        -- Each k' ≠ ⟨j,hj⟩ means k'.val ≠ j, so σ_coord k'.val ≤ sigmaAlgExcept j
        -- Unfold M' to its iSup form and distribute comap over it
        -- M' ≤ comap restrict (sigmaAlgExcept j)
        -- ⟺ ⨆ k' ∈ {⟨j,hj⟩}ᶜ, comap (eval k') inst ≤ comap restrict (sigmaAlgExcept j)
        -- ⟺ ∀ k' ∈ {⟨j,hj⟩}ᶜ, comap (eval k') inst ≤ comap restrict (sigmaAlgExcept j)
        -- Each: comap (eval k') inst = comap (eval k' ∘ restrict ∘ id) inst
        --       but we need: comap (eval k') inst ≤ comap restrict (sigmaAlgExcept j)
        --       ⟺ for all A ∈ inst, (eval k')⁻¹(A) ∈ comap restrict (sigmaAlgExcept j)
        --       ⟺ for all A, ∃ s ∈ sigmaAlgExcept j, (eval k')⁻¹(A) = restrict⁻¹'(s)
        --       This is NOT the right direction for comap.
        -- Actually: comap (eval k') inst ≤ comap restrict (sigmaAlgExcept j)
        --   means: for s ∈ comap (eval k') inst, s ∈ comap restrict (sigmaAlgExcept j)
        --   i.e., for s = (eval k')⁻¹(A), there exists t ∈ sigmaAlgExcept j with s = restrict⁻¹'(t).
        --   Take t = (eval k'.val)⁻¹(A). Then restrict⁻¹'(t) = (eval k'.val)⁻¹(A) = (eval k' ∘ restrict)⁻¹(A)
        --   = (eval k')⁻¹(A) ∘ restrict... hmm.
        -- Let me use a cleaner formulation via le_trans with comap_comp:
        -- comap (eval k') inst = comap (eval k' ∘ restrict⁻¹... no.
        -- Actually: we need to go through the definition.
        -- s ∈ comap (eval k') inst ⟹ s = {y | y k' ∈ A} for some A
        -- This is a set on the SMALL space.
        -- restrict⁻¹'(s) = {x | restrict(x) k' ∈ A} = {x | x k'.val ∈ A}
        -- = (eval k'.val)⁻¹(A) ∈ σ_coord k'.val ≤ sigmaAlgExcept j (since k'.val ≠ j)
        -- So we need: s ∈ comap restrict (sigmaAlgExcept j)
        -- means ∃ u ∈ sigmaAlgExcept j, s = restrict⁻¹'(u)... wait, NO.
        -- comap restrict (sigmaAlgExcept j) = {s on big space | ...}. But s is on the SMALL space!
        -- I think the issue is: comap restrict M' is a σ-algebra on the BIG space.
        -- The original goal is: comap restrict M' ≤ sigmaAlgExcept j (on the big space).
        -- So for s on the BIG space with s ∈ comap restrict M',
        -- we need s ∈ sigmaAlgExcept j (on the big space).
        -- s ∈ comap restrict M' means s = restrict⁻¹'(t) for some t ∈ M' (on small space).
        -- Need: restrict⁻¹'(t) ∈ sigmaAlgExcept j.
        -- This is what we need to show.
        -- The approach: suffices M' ≤ {t small | restrict⁻¹'(t) ∈ sigmaAlgExcept j}
        -- The RHS is MeasurableSpace.comap restrict (sigmaAlgExcept j)... wait:
        -- No! comap restrict (sigmaAlgExcept j) = {s BIG | ∃ t ∈ sigmaAlgExcept j, s = restrict⁻¹'(t)}
        -- That's a σ-algebra on the BIG space, not the small space!
        -- What we want: the set {t SMALL | restrict⁻¹'(t) ∈ sigmaAlgExcept j} as a MeasurableSpace on SMALL.
        -- This is: MeasurableSpace.map restrict (sigmaAlgExcept j)
        -- (map f m = {t | f⁻¹'(t) ∈ m})
        -- So: M' ≤ map restrict (sigmaAlgExcept j)
        -- And this is equivalent to: restrict is (sigmaAlgExcept j, M')-measurable
        -- (by measurable_iff_le_map).
        -- NOW: we can't use measurable_pi_lambda because M' ≤ pi_small but the j-th component
        -- is not sigmaAlgExcept j-measurable.
        -- BUT: M' doesn't include the j-th component!
        -- So we need: M' ≤ map restrict (sigmaAlgExcept j).
        -- Unfold M' and check each generator.
        -- Generator k' ≠ ⟨j,hj⟩: comap (eval k') inst
        -- Need: comap (eval k') inst ≤ map restrict (sigmaAlgExcept j)
        -- i.e., ∀ A, {y | y k' ∈ A} ∈ map restrict (sigmaAlgExcept j)
        -- i.e., ∀ A, restrict⁻¹'({y | y k' ∈ A}) ∈ sigmaAlgExcept j
        -- i.e., ∀ A, {x | x k'.val ∈ A} ∈ sigmaAlgExcept j
        -- i.e., σ_coord k'.val ≤ sigmaAlgExcept j  ✓ (since k'.val ≠ j)
        -- So the proof is: unfold M', iSup₂_le, for each k' show the generator ≤ map restrict M.
        -- And measurable_iff_le_map or direct.
        -- The approach: intro s hs, obtain, then show restrict⁻¹'(t) ∈ sigmaAlgExcept j
        -- by showing M' ≤ map restrict (sigmaAlgExcept j) and hence t ∈ map restrict (sigmaAlgExcept j).
        -- Direct: for t ∈ M', restrict⁻¹'(t) ∈ sigmaAlgExcept j.
        -- We show this by: {t | restrict⁻¹'(t) ∈ sigmaAlgExcept j} is a σ-algebra containing M''s generators.
        -- This σ-algebra is MeasurableSpace.map restrict (sigmaAlgExcept j).
        -- So: suffices M' ≤ MeasurableSpace.map restrict (sigmaAlgExcept j)
        intro s hs
        obtain ⟨t, ht, rfl⟩ := hs
        -- t ∈ M' on small space, need restrict⁻¹'(t) ∈ sigmaAlgExcept j on big space
        suffices h : sigmaAlgExcept (X := fun k : {k : ι // k ≠ i₀} => X k.val) ⟨j, hj⟩ ≤
            MeasurableSpace.map restrict (sigmaAlgExcept (X := X) j) from h t ht
        unfold sigmaAlgExcept
        apply iSup₂_le
        intro k' hk'
        rw [Set.mem_compl_iff, Set.mem_singleton_iff] at hk'
        have hkval_ne_j : k'.val ≠ j := fun h => hk' (Subtype.ext h)
        -- Need: comap (eval k') inst ≤ map restrict (sigmaAlgExcept j)
        -- i.e., ∀ A ∈ inst, restrict⁻¹'({y | y k' ∈ A}) ∈ sigmaAlgExcept j
        -- Since restrict⁻¹'({y | y k' ∈ A}) = {x | x k'.val ∈ A} ∈ σ_coord k'.val ≤ sigmaAlgExcept j
        intro u hu
        obtain ⟨A, hA, rfl⟩ := hu
        change @MeasurableSet _ (sigmaAlgExcept (X := X) j)
          (restrict ⁻¹' ((fun y => y k') ⁻¹' A))
        have : restrict ⁻¹' ((fun y => y k') ⁻¹' A) = (fun x : ∀ l, X l => x k'.val) ⁻¹' A := by
          ext x; simp [restrict]
        rw [this]
        apply σ_coord_le_except (X := X) k'.val j hkval_ne_j
        exact ⟨A, hA, rfl⟩
      -- Step 8a: For each j ≠ i₀, show E_{μ'}[Var[g̃|σ'_j']] = E_μ[Var[g|σ_j]]
      have hterm_eq : ∀ (j : ι) (hj : j ≠ i₀),
          P'[Var[gtil; P' | sigmaAlgExcept ⟨j, hj⟩]] =
          P[Var[g; P | sigmaAlgExcept j]] := by
        intro j hj
        set M := sigmaAlgExcept (X := X) j
        set N := sigmaAlgExcept (X := X) i₀
        have hM : M ≤ MeasurableSpace.pi := sigmaAlgExcept_le (X := X) j
        have hN : N ≤ MeasurableSpace.pi := sigmaAlgExcept_le (X := X) i₀
        -- (a) By commutativity: P[g|M] =ᵃᵉ P[P[f|M]|N]
        have hcomm : P[g | M] =ᵐ[P] P[P[f | M] | N] :=
          condExp_condExp_comm_pi μ f (hf.integrable (by norm_num)) i₀ j hj
        -- P[P[f|M]|N] is N-sm, hence factors through restrict by Doob-Dynkin
        have hfMN_sm : StronglyMeasurable[N] (P[P[f | M] | N]) := stronglyMeasurable_condExp
        obtain ⟨htil, hhtil_sm, hhtil_eq⟩ :=
          (hfMN_sm.mono hle_comap).exists_eq_measurable_comp
        -- hhtil_eq : P[P[f|M]|N] = htil ∘ restrict (pointwise)
        -- Sub-σ-algebra comap inequalities (no `set` to avoid instance pollution)
        have hM' : sigmaAlgExcept (X := fun k : {k : ι // k ≠ i₀} => X k.val) ⟨j, hj⟩ ≤
            MeasurableSpace.pi :=
          sigmaAlgExcept_le (X := fun k : {k : ι // k ≠ i₀} => X k.val) ⟨j, hj⟩
        have hcomap_le_N : MeasurableSpace.comap restrict
            (sigmaAlgExcept (X := fun k : {k : ι // k ≠ i₀} => X k.val) ⟨j, hj⟩) ≤ N :=
          (measurable_iff_comap_le (f := restrict)).mp (hrestrict_N_meas.mono le_rfl hM')
        have hcomap_le_M : MeasurableSpace.comap restrict
            (sigmaAlgExcept (X := fun k : {k : ι // k ≠ i₀} => X k.val) ⟨j, hj⟩) ≤ M :=
          hcomap_M'_le_M j hj
        -- SigmaFinite instances
        haveI hsfM : SigmaFinite (P.trim hM) := by
          have : IsFiniteMeasure (P.trim hM) := by
            constructor; rw [trim_measurableSet_eq hM MeasurableSet.univ]; exact measure_lt_top _ _
          exact this.toSigmaFinite
        haveI hsfN : SigmaFinite (P.trim hN) := by
          have : IsFiniteMeasure (P.trim hN) := by
            constructor; rw [trim_measurableSet_eq hN MeasurableSet.univ]; exact measure_lt_top _ _
          exact this.toSigmaFinite
        haveI hsfM' : SigmaFinite (P'.trim hM') := by
          have : IsFiniteMeasure (P'.trim hM') := by
            constructor; rw [trim_measurableSet_eq hM' MeasurableSet.univ]; exact measure_lt_top _ _
          exact this.toSigmaFinite
        -- (b) Show htil =ᵃᵉ[P'] P'[gtil | M'] via Dynkin π-λ on the big space
        -- Strategy: define condE = P'[gtil|M'], show (htil ∘ restrict) =ᵃᵉ[P] (condE ∘ restrict)
        -- using a π-system based on comap restrict M' (which generates pi), then transfer.
        set M'_full := MeasurableSpace.comap restrict
            (sigmaAlgExcept (X := fun k : {k : ι // k ≠ i₀} => X k.val) ⟨j, hj⟩)
          with hM'_full_def
        -- Restore MeasurableSpace.pi as the default instance (M'_full pollutes synthesis)
        letI : MeasurableSpace (∀ k, X k) := MeasurableSpace.pi
        have hM'_full_le_pi : M'_full ≤ MeasurableSpace.pi :=
          le_trans hcomap_le_N hN
        -- σ_coord k ≤ M'_full for k ≠ i₀ and k ≠ j
        have hcoord_le_M'_full : ∀ (k : ι), k ≠ i₀ → k ≠ j → σ_coord (X := X) k ≤ M'_full := by
          intro k hki hkj
          show σ_coord (X := X) k ≤ MeasurableSpace.comap restrict
            (sigmaAlgExcept (X := fun k : {k : ι // k ≠ i₀} => X k.val) ⟨j, hj⟩)
          have hfact : (fun (x : ∀ l, X l) => x k) =
            (fun (y : ∀ l : {l : ι // l ≠ i₀}, X l.val) => y ⟨k, hki⟩) ∘ restrict := rfl
          rw [show σ_coord (X := X) k =
            MeasurableSpace.comap (fun (x : ∀ l, X l) => x k)
              (inferInstance : MeasurableSpace (X k)) from rfl]
          rw [hfact, ← MeasurableSpace.comap_comp]
          exact MeasurableSpace.comap_mono
            (σ_coord_le_except (X := fun l : {l : ι // l ≠ i₀} => X l.val)
              ⟨k, hki⟩ ⟨j, hj⟩ (fun h => hkj (congr_arg Subtype.val h)))
        -- piSys' based on comap restrict M'
        let piSys' : Set (Set (∀ k, X k)) :=
          {s | ∃ (A B C : Set (∀ k, X k)),
            @MeasurableSet _ M'_full A ∧
            @MeasurableSet _ (σ_coord (X := X) i₀) B ∧
            @MeasurableSet _ (σ_coord (X := X) j) C ∧
            s = A ∩ B ∩ C}
        have hpiSys'_pi : IsPiSystem piSys' := by
          intro s₁ hs₁ s₂ hs₂ _hne
          obtain ⟨A₁, B₁, C₁, hA₁, hB₁, hC₁, rfl⟩ := hs₁
          obtain ⟨A₂, B₂, C₂, hA₂, hB₂, hC₂, rfl⟩ := hs₂
          exact ⟨A₁ ∩ A₂, B₁ ∩ B₂, C₁ ∩ C₂, hA₁.inter hA₂, hB₁.inter hB₂, hC₁.inter hC₂,
            by ext x; simp [Set.mem_inter_iff]; tauto⟩
        have hpiSys'_gen : MeasurableSpace.pi = MeasurableSpace.generateFrom piSys' := by
          apply le_antisymm
          · rw [show (MeasurableSpace.pi : MeasurableSpace (∀ k, X k)) =
              ⨆ k, σ_coord (X := X) k from rfl]
            refine iSup_le ?_
            intro k s hs
            apply MeasurableSpace.measurableSet_generateFrom
            by_cases hki : k = i₀
            · subst hki
              exact ⟨Set.univ, s, Set.univ, MeasurableSet.univ, hs, MeasurableSet.univ, by simp⟩
            · by_cases hkj : k = j
              · subst hkj
                exact ⟨Set.univ, Set.univ, s, MeasurableSet.univ, MeasurableSet.univ, hs, by simp⟩
              · exact ⟨s, Set.univ, Set.univ,
                  hcoord_le_M'_full k hki hkj s hs,
                  MeasurableSet.univ, MeasurableSet.univ, by simp⟩
          · refine generateFrom_le ?_
            intro s hs
            obtain ⟨A, B, C, hA, hB, hC, rfl⟩ := hs
            exact ((hM'_full_le_pi A hA).inter
              (σ_coord_le_pi (X := X) i₀ B hB)).inter (σ_coord_le_pi (X := X) j C hC)
        have hhtil_int : Integrable htil P' := by
          rw [← hpi_map,
              integrable_map_measure hhtil_sm.aestronglyMeasurable hf_meas.aemeasurable,
              ← hhtil_eq]
          exact integrable_condExp
        -- condE on the small space
        set condE := P'[gtil |
            sigmaAlgExcept (X := fun k : {k : ι // k ≠ i₀} => X k.val) ⟨j, hj⟩]
          with hcondE_def
        have hcondE_int : Integrable condE P' := integrable_condExp
        -- condE ∘ restrict is (comap restrict M')-StronglyMeasurable hence N-sm and M-sm
        have hcondE_comp_sm : @StronglyMeasurable _ _ _ M'_full (condE ∘ restrict) :=
          @StronglyMeasurable.comp_measurable _ _ _ _
            (sigmaAlgExcept (X := fun k : {k : ι // k ≠ i₀} => X k.val) ⟨j, hj⟩)
            M'_full condE restrict stronglyMeasurable_condExp
            ((measurable_iff_comap_le (f := restrict)).mpr le_rfl)
        have hcondE_comp_N_sm : @StronglyMeasurable _ _ _ N (condE ∘ restrict) :=
          hcondE_comp_sm.mono hcomap_le_N
        have hcondE_comp_M_sm : @StronglyMeasurable _ _ _ M (condE ∘ restrict) :=
          hcondE_comp_sm.mono hcomap_le_M
        have hcondE_comp_int : Integrable (condE ∘ restrict) P := by
          have hint : Integrable condE (P.map restrict) := by rw [hpi_map]; exact hcondE_int
          exact hint.comp_measurable hf_meas
        -- d = P[P[f|M]|N] - condE ∘ restrict on the big space
        have hd_int : Integrable
            (fun ω => P[P[f | M] | N] ω - (condE ∘ restrict) ω) P :=
          integrable_condExp.sub hcondE_comp_int
        -- ∫ d = 0
        have hd_zero : ∫ x, (P[P[f | M] | N] x - (condE ∘ restrict) x) ∂P = 0 := by
          rw [integral_sub integrable_condExp hcondE_comp_int]
          have h1 : ∫ x, P[P[f | M] | N] x ∂P = ∫ x, f x ∂P := by
            rw [integral_condExp hN, integral_condExp hM]
          have h2 : ∫ x, (condE ∘ restrict) x ∂P = ∫ x, f x ∂P := by
            have hcondE_sm_pi : AEStronglyMeasurable condE (P.map restrict) :=
              hpi_map ▸ (stronglyMeasurable_condExp.mono hM').aestronglyMeasurable
            have hstep1 : ∫ x, (condE ∘ restrict) x ∂P = ∫ x, condE x ∂P' := by
              rw [show (fun x => (condE ∘ restrict) x) = (fun x => condE (restrict x)) from rfl]
              rw [← integral_map hf_meas.aemeasurable hcondE_sm_pi, hpi_map]
            have hgtil_sm_pi : AEStronglyMeasurable gtil (P.map restrict) := by
              rw [hpi_map]; exact hgtil_sm.aestronglyMeasurable
            have hstep2 : ∫ x, gtil x ∂P' = ∫ x, (gtil ∘ restrict) x ∂P := by
              rw [show (fun x => (gtil ∘ restrict) x) = (fun x => gtil (restrict x)) from rfl]
              rw [← integral_map hf_meas.aemeasurable hgtil_sm_pi, hpi_map]
            rw [hstep1, integral_condExp hM', hstep2,
              show (fun x => (gtil ∘ restrict) x) = g from hg_factor.symm]
            exact integral_condExp hN
          rw [h1, h2, sub_self]
        -- ∫_s d = 0 for s ∈ piSys'
        have h_piSys' : ∀ s ∈ piSys', ∫ x in s,
            (P[P[f | M] | N] x - (condE ∘ restrict) x) ∂P = 0 := by
          intro s hs
          obtain ⟨A, B, C, hA, hB, hC, rfl⟩ := hs
          have hA_N : @MeasurableSet _ N A := hcomap_le_N A hA
          have hA_M : @MeasurableSet _ M A := hcomap_le_M A hA
          have hB_M : @MeasurableSet _ M B :=
            σ_coord_le_except (X := X) i₀ j (Ne.symm hj) B hB
          have hC_N : @MeasurableSet _ N C :=
            σ_coord_le_except (X := X) j i₀ hj C hC
          have hAB_M : @MeasurableSet _ M (A ∩ B) := hA_M.inter hB_M
          have hAC_N : @MeasurableSet _ N (A ∩ C) := hA_N.inter hC_N
          have hM_indep_j := indep_sigmaAlgExcept_coord μ j
          have hN_indep_i := indep_sigmaAlgExcept_coord μ i₀
          -- LHS integral: ∫_{A∩B∩C} P[P[f|M]|N] = P.real(C) * P.real(B) * ∫_A f
          -- Chain: factor B via N⊥σ_{i₀} → tower N on A∩C → factor C via M⊥σ_j → tower M on A
          have hfM_int : Integrable (P[f | M]) P := integrable_condExp
          have hfMN_int : Integrable (P[P[f | M] | N]) P := integrable_condExp
          have hLHS : ∫ x in A ∩ B ∩ C, P[P[f | M] | N] x ∂P =
              P.real C * P.real B * ∫ x in A, f x ∂P := by
            have h1 : ∫ x in A ∩ B ∩ C, P[P[f | M] | N] x ∂P =
                (∫ x in A ∩ C, P[P[f | M] | N] x ∂P) * P.real B := by
              rw [show A ∩ B ∩ C = B ∩ (A ∩ C) from by ext x; simp [Set.mem_inter_iff]; tauto]
              rw [← setIntegral_indicator (hN (A ∩ C) hAC_N)]
              rw [setIntegral_eq_integral_mul_meas_of_indep μ hN
                (σ_coord_le_pi (X := X) i₀) hN_indep_i
                (hfMN_int.indicator (hN (A ∩ C) hAC_N))
                (stronglyMeasurable_condExp.indicator hAC_N) hB]
              rw [integral_indicator (hN (A ∩ C) hAC_N)]
            have h2 : ∫ x in A ∩ C, P[P[f | M] | N] x ∂P =
                ∫ x in A ∩ C, P[f | M] x ∂P :=
              setIntegral_condExp hN hfM_int hAC_N
            have h3 : ∫ x in A ∩ C, P[f | M] x ∂P =
                (∫ x in A, P[f | M] x ∂P) * P.real C := by
              rw [Set.inter_comm A C, ← setIntegral_indicator (hM A hA_M)]
              rw [setIntegral_eq_integral_mul_meas_of_indep μ hM
                (σ_coord_le_pi (X := X) j) hM_indep_j
                (hfM_int.indicator (hM A hA_M))
                (stronglyMeasurable_condExp.indicator hA_M) hC]
              rw [integral_indicator (hM A hA_M)]
            have h4 : ∫ x in A, P[f | M] x ∂P = ∫ x in A, f x ∂P :=
              setIntegral_condExp hM (hf.integrable (by norm_num)) hA_M
            rw [h1, h2, h3, h4]; ring
          -- RHS integral: ∫_{A∩B∩C} (condE ∘ restrict) = P.real(C) * P.real(B) * ∫_A f
          -- Same chain: condE ∘ restrict is N-sm AND M-sm (via comap ≤ N ∩ M)
          have hRHS : ∫ x in A ∩ B ∩ C, (condE ∘ restrict) x ∂P =
              P.real C * P.real B * ∫ x in A, f x ∂P := by
            have h1 : ∫ x in A ∩ B ∩ C, (condE ∘ restrict) x ∂P =
                (∫ x in A ∩ C, (condE ∘ restrict) x ∂P) * P.real B := by
              rw [show A ∩ B ∩ C = B ∩ (A ∩ C) from by ext x; simp [Set.mem_inter_iff]; tauto]
              rw [← setIntegral_indicator (hN (A ∩ C) hAC_N)]
              rw [setIntegral_eq_integral_mul_meas_of_indep μ hN
                (σ_coord_le_pi (X := X) i₀) hN_indep_i
                (hcondE_comp_int.indicator (hN (A ∩ C) hAC_N))
                (hcondE_comp_N_sm.indicator hAC_N) hB]
              rw [integral_indicator (hN (A ∩ C) hAC_N)]
            -- ∫_{A∩C} (condE ∘ restrict) = ∫_A (condE ∘ restrict) · P.real(C)
            have h3 : ∫ x in A ∩ C, (condE ∘ restrict) x ∂P =
                (∫ x in A, (condE ∘ restrict) x ∂P) * P.real C := by
              rw [Set.inter_comm A C, ← setIntegral_indicator (hM A hA_M)]
              rw [setIntegral_eq_integral_mul_meas_of_indep μ hM
                (σ_coord_le_pi (X := X) j) hM_indep_j
                (hcondE_comp_int.indicator (hM A hA_M))
                (hcondE_comp_M_sm.indicator hA_M) hC]
              rw [integral_indicator (hM A hA_M)]
            -- ∫_A (condE ∘ restrict) = ∫_A f (via map + condExp on M'-set + tower on N)
            have h4 : ∫ x in A, (condE ∘ restrict) x ∂P = ∫ x in A, f x ∂P := by
              -- A ∈ comap restrict M', so A = restrict⁻¹(A') for some A' ∈ M'
              obtain ⟨A', hA'_M', hA_eq⟩ := hA
              rw [← hA_eq]
              -- ∫_{restrict⁻¹(A')} (condE ∘ restrict) = ∫_{A'} condE dP'
              have step1 : ∫ x in restrict ⁻¹' A', (condE ∘ restrict) x ∂P =
                  ∫ x in A', condE x ∂P' := by
                rw [← hpi_map]
                have hcondE_sm' : AEStronglyMeasurable condE (P.map restrict) :=
                  hpi_map ▸ (stronglyMeasurable_condExp.mono hM').aestronglyMeasurable
                exact (setIntegral_map (hM' A' hA'_M') hcondE_sm'
                  hf_meas.aemeasurable).symm
              -- ∫_{A'} condE dP' = ∫_{A'} gtil dP' (condExp on M'-meas set)
              have step2 : ∫ x in A', condE x ∂P' = ∫ x in A', gtil x ∂P' :=
                setIntegral_condExp hM' (hgtil_memlp.integrable (by norm_num)) hA'_M'
              -- ∫_{A'} gtil dP' = ∫_{restrict⁻¹(A')} g dP (map back + g = gtil ∘ restrict)
              have step3 : ∫ x in A', gtil x ∂P' =
                  ∫ x in restrict ⁻¹' A', g x ∂P := by
                rw [← hpi_map]
                have hgtil_sm' : AEStronglyMeasurable gtil (P.map restrict) :=
                  hpi_map ▸ hgtil_sm.aestronglyMeasurable
                rw [setIntegral_map (hM' A' hA'_M') hgtil_sm' hf_meas.aemeasurable]
                exact integral_congr_ae (ae_restrict_of_ae
                  (ae_of_all P fun x => (congrFun hg_factor x).symm))
              -- ∫_{restrict⁻¹(A')} g dP = ∫_{restrict⁻¹(A')} f dP (tower on N)
              have hA_N' : @MeasurableSet _ N (restrict ⁻¹' A') := by rw [hA_eq]; exact hA_N
              have step4 : ∫ x in restrict ⁻¹' A', g x ∂P =
                  ∫ x in restrict ⁻¹' A', f x ∂P := by
                show ∫ x in restrict ⁻¹' A', P[f | N] x ∂P = _
                exact setIntegral_condExp hN (hf.integrable (by norm_num)) hA_N'
              linarith [step1, step2, step3, step4]
            rw [h1, h3, h4]; ring
          rw [integral_sub integrable_condExp.integrableOn hcondE_comp_int.integrableOn,
              hLHS, hRHS, sub_self]
        -- Dynkin extension: d =ᵃᵉ 0
        have hd_ae : (fun ω => P[P[f | M] | N] ω - (condE ∘ restrict) ω) =ᵐ[P] 0 := by
          rw [show (0 : (∀ j, X j) → ℝ) = fun _ => (0 : ℝ) from rfl]
          refine Integrable.ae_eq_of_forall_setIntegral_eq _ _ hd_int (integrable_const 0)
            (fun s hs _hμs => ?_)
          simp only [integral_const, smul_eq_mul, mul_zero]
          refine @MeasurableSpace.induction_on_inter _ _
            (fun s _ => ∫ x in s, (P[P[f | M] | N] x - (condE ∘ restrict) x) ∂P = 0)
            piSys' hpiSys'_gen hpiSys'_pi ?_ ?_ ?_ ?_ s hs
          · simp
          · exact fun t ht => h_piSys' t ht
          · intro t ht ht_zero
            rw [setIntegral_compl ht hd_int]; linarith
          · intro gs hpwd hgm hgs
            rw [integral_iUnion hgm hpwd hd_int.integrableOn]
            simp only [hgs, tsum_zero]
        -- Transfer: htil =ᵃᵉ[P'] condE
        have hhtil_condExp : htil =ᵐ[P'] condE := by
          -- htil ∘ restrict = P[P[f|M]|N] pointwise, and d =ᵃᵉ[P] 0
          -- ⟹ (htil - condE) ∘ restrict =ᵃᵉ[P] 0 ⟹ htil - condE =ᵃᵉ[P'] 0
          have hae_big : ∀ᵐ ω ∂P, htil (restrict ω) = condE (restrict ω) := by
            filter_upwards [hd_ae] with ω hω
            have h1 : P[P[f | M] | N] ω = htil (restrict ω) := congrFun hhtil_eq ω
            -- hω : (fun ω => ... - ...) ω = 0 ω, i.e., ... - ... = 0
            have h2 : P[P[f | M] | N] ω - condE (restrict ω) = 0 := by
              have := hω; simp only [Pi.zero_apply, Function.comp_apply] at this; exact this
            linarith
          -- Transfer: ∀ᵐ ω ∂P, p(restrict ω) → ∀ᵐ y ∂(P.map restrict), p y
          have hae_small : ∀ᵐ y ∂(P.map restrict), htil y = condE y := by
            rw [ae_map_iff hf_meas.aemeasurable
              (hhtil_sm.measurableSet_eq_fun (stronglyMeasurable_condExp.mono hM'))]
            exact hae_big
          rw [hpi_map] at hae_small; exact hae_small
        -- (c) Variance transfer: Var[E[g|M]; P] = Var[E'[g̃|M']; P']
        have hvar_EgM : Var[P[g | M]; P] = Var[P'[gtil |
            sigmaAlgExcept (X := fun k : {k : ι // k ≠ i₀} => X k.val) ⟨j, hj⟩]; P'] := by
          have hstep1 : Var[P[g | M]; P] = Var[P[P[f | M] | N]; P] := variance_congr hcomm
          have hstep2 : Var[P[P[f | M] | N]; P] = Var[htil ∘ restrict; P] :=
            variance_congr (show P[P[f | M] | N] =ᵐ[P] htil ∘ restrict from by rw [hhtil_eq])
          have hstep3 : Var[htil ∘ restrict; P] = Var[htil; P'] := by
            have := variance_map (Y := restrict) (μ := P) hhtil_sm.aemeasurable hf_meas.aemeasurable
            rw [hpi_map] at this; linarith
          have hstep4 : Var[htil; P'] = Var[P'[gtil |
              sigmaAlgExcept (X := fun k : {k : ι // k ≠ i₀} => X k.val) ⟨j, hj⟩]; P'] :=
            variance_congr hhtil_condExp
          linarith [hstep1, hstep2, hstep3, hstep4]
        -- LTV on both sides
        have hltv_gM := integral_condVar_add_variance_condExp hM (μ := P) hg
        have hltv_gtilM' := integral_condVar_add_variance_condExp hM' (μ := P') hgtil_memlp
        linarith [hltv_gM, hltv_gtilM', hvar_eq, hvar_EgM]
      -- Step 8b: Assemble the sum inequality
      -- ∑_j P[Var[g|σ_j]] = P[Var[g|σ_{i₀}]] + ∑_{j≠i₀} P[Var[g|σ_j]]
      --                    = 0 + ∑_{j≠i₀} P'[Var[g̃|σ'_{j'}]]  (by hltv_g + hterm_eq)
      --                    = ∑_j' P'[Var[g̃|σ'_j']]
      --                    ≥ Var[g̃] = Var[g]                    (by hih + hvar_eq)
      have hsum_transfer : ∑ j' : {j : ι // j ≠ i₀},
          P'[Var[gtil; P' | sigmaAlgExcept j']] =
          ∑ j ∈ Finset.univ.erase i₀,
            P[Var[g; P | sigmaAlgExcept j]] := by
        -- Rewrite LHS term-by-term
        have : ∀ j' : {j : ι // j ≠ i₀},
            P'[Var[gtil; P' | sigmaAlgExcept j']] =
            P[Var[g; P | sigmaAlgExcept j'.val]] := fun ⟨j, hj⟩ => hterm_eq j hj
        simp_rw [this]
        -- Now: ∑ j' : {j // j ≠ i₀}, F j'.val = ∑ j ∈ univ.erase i₀, F j
        symm
        apply Finset.sum_subtype
        intro x
        simp [Finset.mem_erase]
      calc Var[g; Measure.pi μ]
          = Var[gtil; Measure.pi μ'] := hvar_eq
        _ ≤ ∑ j' : {j : ι // j ≠ i₀},
              P'[Var[gtil; P' | sigmaAlgExcept j']] := hih
        _ = ∑ j ∈ Finset.univ.erase i₀,
              P[Var[g; P | sigmaAlgExcept j]] := hsum_transfer
        _ ≤ 0 + ∑ j ∈ Finset.univ.erase i₀,
              P[Var[g; P | sigmaAlgExcept j]] := by linarith
        _ = P[Var[g; P | sigmaAlgExcept i₀]] +
            ∑ j ∈ Finset.univ.erase i₀,
              P[Var[g; P | sigmaAlgExcept j]] := by rw [← hltv_g]
        _ = ∑ j : ι, P[Var[g; P | sigmaAlgExcept j]] := by
            rw [← Finset.sum_erase_add Finset.univ _ (Finset.mem_univ i₀), add_comm]
    -- Split the g sum and use hltv_g for the i₀ term
    have hg_sum_split :
        ∑ j : ι, (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] =
        (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept i₀]] +
        ∑ j ∈ Finset.univ.erase i₀,
          (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] :=
      (Finset.sum_erase_add Finset.univ _ (Finset.mem_univ i₀)).symm.trans (add_comm _ _)
    -- For each j ≠ i₀, use efron_stein_condVar_le_of_condExp
    have hg_le_f : ∀ j ∈ Finset.univ.erase i₀,
        (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] ≤
        (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept j]] := by
      intro j hj
      have hjne : j ≠ i₀ := Finset.ne_of_mem_erase hj
      exact efron_stein_condVar_le_of_condExp μ f hf i₀ j hjne
    -- Combine
    have hg_bound : Var[g; Measure.pi μ] ≤
        ∑ j ∈ Finset.univ.erase i₀,
          (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept j]] := by
      calc Var[g; Measure.pi μ]
          ≤ ∑ j : ι, (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] := hg_es
        _ = (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept i₀]] +
            ∑ j ∈ Finset.univ.erase i₀,
              (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] := hg_sum_split
        _ = 0 + ∑ j ∈ Finset.univ.erase i₀,
              (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] := by
            rw [hltv_g]
        _ = ∑ j ∈ Finset.univ.erase i₀,
              (Measure.pi μ)[Var[g; Measure.pi μ | sigmaAlgExcept j]] := by
            ring
        _ ≤ ∑ j ∈ Finset.univ.erase i₀,
              (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept j]] :=
            Finset.sum_le_sum hg_le_f
    linarith [hltv, hg_bound, hsum_f.ge]

theorem efron_stein_core
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] :=
  efron_stein_core_gen (Fintype.card ι) μ f rfl hf

lemma efron_stein_anova_key
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    ∑ i : ι,
      Var[(Measure.pi μ)[f | sigmaAlgExcept i]; Measure.pi μ] ≤
    ((Fintype.card ι : ℝ) - 1) * Var[f; Measure.pi μ] := by
  have hltv : ∀ i : ι,
      (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]] +
        Var[(Measure.pi μ)[f | sigmaAlgExcept i]; Measure.pi μ] = Var[f; Measure.pi μ] :=
    fun i => integral_condVar_add_variance_condExp (sigmaAlgExcept_le (X := X) i)
              (μ := Measure.pi μ) hf
  have hsum :
      (∑ i : ι, (Measure.pi μ)[Var[f; Measure.pi μ | sigmaAlgExcept i]]) +
        (∑ i : ι, Var[(Measure.pi μ)[f | sigmaAlgExcept i]; Measure.pi μ]) =
        (Fintype.card ι : ℝ) * Var[f; Measure.pi μ] := by
    rw [← Finset.sum_add_distrib]
    simp_rw [hltv]
    simp [Finset.sum_const, nsmul_eq_mul]
  have hES := efron_stein_core (μ := μ) f hf
  linarith

theorem efron_stein
    [∀ i, IsProbabilityMeasure (μ i)]
    (f : (∀ j, X j) → ℝ)
    (hf : MemLp f 2 (Measure.pi μ)) :
    Var[f; Measure.pi μ] ≤
      ∑ i : ι, ∫ ω, (f ω - condExpExceptCoord μ i f ω) ^ 2 ∂(Measure.pi μ) :=
  efron_stein_of_condVar_sum_bound (μ := μ) f hf (efron_stein_core (μ := μ) f hf)

end
