import Mathlib

/-!
# NormSubAddBound

Promoted from prove session: `cli-20260413-norm_sub_add_bound-qcy0`
Target theorem: `Statlean.EvolveT5.norm_sub_add_bound`
Original file: `Statlean/Web/evolve_t5_norm_tri/Main.lean`
Cost: $0.097, 8 turns, claude-sonnet-4-6

Generated by evolve/applier/lemma.ts on 2026-04-13.
-/

namespace Statlean.Analysis.Norm

variable {V : Type*} [SeminormedAddCommGroup V]

theorem norm_sub_add_bound (a b c : V) :
    ‖a + b - c‖ ≤ ‖a - c‖ + ‖b‖ := by
  have h : a + b - c = (a - c) + b := by abel
  rw [h]
  exact norm_add_le (a - c) b

end Statlean.Analysis.Norm
