import Mathlib

/-!
# CoxS3CauchySchwarzTail

Promoted from prove session: `cli-20260413-cox_s3_cauchy_schwarz_tail-z322`
Target theorem: `Statlean.CoxS3.cox_s3_cauchy_schwarz_tail`
Original file: `Statlean/Web/evolve_cox_s3_cs/Main.lean`
Cost: $0.382, 32 turns, claude-sonnet-4-6

Generated by evolve/applier/lemma.ts on 2026-04-14.
-/

namespace Statlean.Misc

theorem cox_s3_cauchy_schwarz_tail
    (N d : ℕ) (ξ α : ℕ → ℝ) :
    |∑ k ∈ Finset.Ico N d, ξ k * α k|
      ≤ Real.sqrt (∑ k ∈ Finset.Ico N d, (ξ k)^2)
        * Real.sqrt (∑ k ∈ Finset.Ico N d, (α k)^2) := by
  have hub := Real.sum_mul_le_sqrt_mul_sqrt (Finset.Ico N d) ξ α
  have hneg := Real.sum_mul_le_sqrt_mul_sqrt (Finset.Ico N d) (fun k => -ξ k) α
  have hneg_sum : ∑ k ∈ Finset.Ico N d, (-ξ k) * α k =
      -(∑ k ∈ Finset.Ico N d, ξ k * α k) := by
    simp [neg_mul, Finset.sum_neg_distrib]
  have hneg_sq : ∑ k ∈ Finset.Ico N d, (-ξ k) ^ 2 =
      ∑ k ∈ Finset.Ico N d, (ξ k) ^ 2 := by
    congr 1; ext k; ring
  rw [hneg_sum, hneg_sq] at hneg
  rw [abs_le]
  constructor
  · linarith
  · exact hub

end Statlean.Misc
