import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.Independence.Integration
import Mathlib.MeasureTheory.Measure.FiniteMeasurePi
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Probability.CondVar
import Mathlib.MeasureTheory.Function.L2Space

/-! # Concentration Inequalities — Shared Definitions

This module provides common definitions used across the concentration inequality proofs
in the paper "Statistical Learning Theory in Lean 4".

## Main definitions

* `condExpExceptCoord` — conditional expectation "resampling" coordinate i
* `variancePi` — variance of f(X₁,...,Xₙ) under product measure

## Key setup

We work with a finite product probability space:
  Ω = ∏ᵢ Xᵢ, μ = ⊗ᵢ μᵢ (product of probability measures)
  X₁,...,Xₙ are independent (coordinates of the product)
-/

open MeasureTheory ProbabilityTheory MeasurableSpace

noncomputable section

variable {ι : Type*} [Fintype ι]
variable {X : ι → Type*} [∀ i, MeasurableSpace (X i)]
variable (μ : ∀ i, Measure (X i))

/-- The product probability measure on `∏ i, X i`. -/
abbrev prodMeasure : Measure (∀ i, X i) := Measure.pi μ

/-- The sigma-algebra generated by all coordinates except `i`.
    This is `⨆ j ≠ i, MeasurableSpace.comap (fun x => x j) (X j)`. -/
def sigmaAlgExcept (i : ι) : MeasurableSpace (∀ j, X j) :=
  ⨆ j ∈ ({i}ᶜ : Set ι), MeasurableSpace.comap (fun x => x j) (‹∀ j, MeasurableSpace (X j)› j)

set_option linter.unusedSectionVars false in
set_option linter.unusedFintypeInType false in
/-- `sigmaAlgExcept i` is a sub-σ-algebra of the ambient product measurable space. -/
lemma sigmaAlgExcept_le (i : ι) :
    sigmaAlgExcept (X := X) i ≤ (inferInstance : MeasurableSpace (∀ j, X j)) := by
  classical
  refine iSup₂_le ?_
  intro j hj
  exact le_iSup (fun a : ι =>
    MeasurableSpace.comap (fun x : (∀ b, X b) => x a)
      (inferInstance : MeasurableSpace (X a))) j

set_option linter.unusedSectionVars false in
set_option linter.unusedFintypeInType false in
/-- If there is only one coordinate, forgetting that coordinate gives the trivial σ-algebra. -/
lemma sigmaAlgExcept_eq_bot [Unique ι] (i : ι) :
    sigmaAlgExcept (X := X) i = (⊥ : MeasurableSpace (∀ j, X j)) := by
  have hcomp : ({i}ᶜ : Set ι) = ∅ := by
    ext j
    simp [Subsingleton.elim j i]
  simp [sigmaAlgExcept, hcomp]

/-- Conditional expectation of `f` given all coordinates except `i`.
    Denoted E^{(i)}[f] in the paper (Efron-Stein context).
    This is `E[f | σ(Xⱼ : j ≠ i)]`. -/
def condExpExceptCoord (i : ι) (f : (∀ j, X j) → ℝ) :
    (∀ j, X j) → ℝ :=
  (Measure.pi μ)[f | sigmaAlgExcept i]

end
