import Statlean.Basic

/-! # ExpFamily/Basic

Pipeline-generated declarations for ExpFamily.Basic.
-/

namespace Statlean.ExpFamily.Basic

end Statlean.ExpFamily.Basic

section PipelineGenerated
/-! Declarations generated by the pipeline. -/

/-
ID: concept.exponential_family
Title: Exponential Family
Kind: definition
PIPELINE_ID: concept.exponential_family

LaTeX statement:
(empty)

LaTeX proof hint:
(empty)
-/
def exponential_family : Prop := sorry  -- TODO: fill Lean definition

end PipelineGenerated
