#!/usr/bin/env python3
"""Generate StatLean API index (name → file:line → kind).

Usage:
  python3 scripts/gen_statlean_index.py > theme/statlean_api_index.tsv

Regenerate after adding new theorems/defs.
"""

import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent


def main():
    entries = []
    for lean_file in sorted(PROJECT_ROOT.glob("Statlean/**/*.lean")):
        rel = lean_file.relative_to(PROJECT_ROOT)
        for i, line in enumerate(lean_file.read_text().split("\n"), 1):
            m = re.match(
                r"(theorem|lemma|noncomputable def|def|private theorem|private lemma|private def|abbrev|noncomputable abbrev)\s+"
                r"([a-zA-Z_][\w.]*)",
                line,
            )
            if m:
                kind = m.group(1)
                name = m.group(2)
                entries.append((name, f"{rel}:{i}", kind))

    # Header
    print(f"# StatLean API index — {len(entries)} declarations")
    print(f"# Generated by scripts/gen_statlean_index.py")
    print(f"# Format: name<TAB>file:line<TAB>kind")
    print(f"# Usage: grep -i '<keyword>' theme/statlean_api_index.tsv")
    for name, loc, kind in sorted(entries):
        print(f"{name}\t{loc}\t{kind}")


if __name__ == "__main__":
    main()
