import Statlean.Basic

/-! # Pipeline/Lecture9Handout

Pipeline-generated declarations for Pipeline.Lecture9Handout.
-/

namespace Statlean.Pipeline.Lecture9Handout

end Statlean.Pipeline.Lecture9Handout

section PipelineGenerated
/-! Declarations generated by the pipeline. -/

/-
ID: lecture_9_handout.theorem.002.scheffe_theorem
Title: Theorem 2
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.002.scheffe_theorem

LaTeX statement:
s on Scheff´es theorem


  - _ν_ is usually the Lebesgue measure or the counting measure

  - e.g. _Xn_ ∼ Binom( _n,pn_ ) and if _npn_ → _λ_, then _Xn_ → _D_ _X_ ∼ Poisson( _λ_ )

    - The pmf of _Xn_ is


_fn_ ( _k_ ) = ( _[n]_ _n_ [(][1][ −] _[p][n]_ [)] _[n]_ [−] _[k]_
_k_ [)] _[p][k]_


    - Note that _pn_ → 0, and _fn_ ( _k_ ) converges pointwise (for each
_k_ = 0 _,_ 1 _,_ 2 _,..._ ) to

_f_ ( _k_ ) = _e_ [−] _[λ][ λ][k]_

_k_ ! _[.]_


Hence _Xn_ →D _X_ ∼ Poisson( _λ_ ) under the counting measure.


LIN Zhenhua (NUS) Lecture 9 4 / 28


- e.g. _Xn_ ∼ _tn_, then _Xn_ →D _X_ ∼ _N_ (0 _,_ 1): The density of _Xn_ is



Γ ( _[n]_ [+][1]
_fn_ ( _x_ ) = ~~√~~ 2




_[x]_ [2]

_n_ _n_

2 [) (][1][ +]



_n_ [)]



Γ ( _[n]_ [+][1]

2 [)]
~~√~~ _nπ_ Γ ( _n_




- _[n]_ [+][1]

2



satisfies _fn_ ( _x_ ) → _ϕ_ ( _x_ ) = (2 _π_ ) [−][1][/][2] _e_ [−] _[x]_ [2][/][2] pointwise.

 - Note that we use the asymptotic property of gamma function:
Γ( _x_ + _α_ ) ∼ Γ( _x_ ) _x_ _[α]_ as _x_ →+∞, for any fixed _α_


LIN Zhenhua (NUS) Lecture 9 5 / 28


# δ -Method

If we have an approximate distribution of _θ_ [ˆ] (often by CLT), what is the
approximate distribution of _g_ ( _θ_ [ˆ] ) for a sm
...

LaTeX proof hint:
(empty)
-/
theorem scheffe_theorem : True := by
  sorry

/-
ID: lecture_9_handout.theorem.003.theorem_3
Title: Theorem 3
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.003.theorem_3

LaTeX statement:
Let _X_ 1 _,X_ 2 _,..._, _Y_ be random variables, and { _an_ } is a sequence
of positive numbers with lim _n_ →∞ _an_ = ∞ satisfying


_D_
_an_ ( _Xn_             - _c_ ) → _Y,_
where _c_ ∈R. Let _g_ be a function from R to R.


(i) If _g_ is differentiable at _c_, then


_an_ [ _g_ ( _Xn_ ) − _g_ ( _c_ )] → _D_ _g_ ′( _c_ ) _Y_
where _g_ [′] ( _x_ ) is the derivatives of _g_ at _x_
(ii) Suppose that _g_ has continuous derivatives of order _m_ - 1 in a
neighborhood of _c_, s.t.
_g_ [(] _[j]_ [)] ( _c_ ) = 0 for all 1 ≤ _j_ ≤ _m_   - 1, and _g_ [(] _[m]_ [)] ( _c_ ) ≠ 0. Then


_D_ 1
_a_ _[m]_ _n_ [[] _[g]_ [ (] _[X][n]_ [) −] _[g]_ [(] _[c]_ [)]] → _[m]_

_m_ ! _[g]_ [(] _[m]_ [)][(] _[c]_ [)] _[Y]_


LIN Zhenhua (NUS) Lecture 9 7 / 28

LaTeX proof hint:
(empty)
-/
theorem theorem_003_theorem_3 : True := by
  sorry

/-
ID: lecture_9_handout.theorem.005.theorem_5
Title: Theorem 5
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.005.theorem_5

LaTeX statement:
s

Suppose _X_ 1 _,...,Xn_ IID with Var( _X_ 1) = 1, _X_ _n_ = _n_ [−][1] ∑ _[n]_ _i_ =1 _[X][i]_ [,] _[c]_ [ =][ E] _[X]_ [1][,]
_an_ = ~~[√]~~ _n_, and _Z_ ∼ _N_ (0 _,_ 1)

  - If _g_ ( _x_ ) = _x_ [2],

    - if _c_ ≠ 0 then ~~[√]~~ _n_ ( _X_ ~~2~~ _n_ [−] _[c]_ [2][)] → _D_ _N_ (0 _,_ 4 _c_ 2) since _g_ ′( _c_ ) = 2 _c_ ;

    - if _c_ = 0, then _g_ [′] ( _c_ ) = 0 but _g_ [′′] ( _c_ ) = 2 ≠ 0, so we have

( ~~[√]~~ _n_ ) [2] ( _X_ ~~2~~ _n_ [−] [0][)] → _D_ _Z_ 2 ∼ _χ_ 21

  - If _g_ ( _x_ ) = _x_ [−][1] and _c_ ≠ 0, then ~~[√]~~ _n_ ( _X_ ~~−~~ _n_ 1 [−] _[c]_ [−][1][)] → _D_ _N_ (0 _,_ 1/ _c_ 4), since
_g_ [′] ( _c_ ) = − _c_ [−][2] .


LIN Zhenhua (NUS) Lecture 9 9 / 28

LaTeX proof hint:
(empty)
-/
theorem theorem_005_theorem_5 : True := by
  sorry

/-
ID: lecture_9_handout.theorem.008.continuous_mapping_theorem
Title: Theorem 8
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.008.continuous_mapping_theorem

LaTeX statement:
s


  - Like the consistency, the asymptotic bias is a concept relating to
sequences { _Tn_ } and { [˜] _bTn_ ( _P_ )}

  - When both the exact bias _bTn_ ( _P_ ) and the asymptotic bias [˜] _bTn_ ( _P_ )
exist, they are NOT necessarily the same

  - If _Tn_ is a consistent estimator of _θ_, then _Tn_ = _θ_ + _op_ (1), and thus _Tn_
is asymptotically unbiased

    - _g_ ( _Tn_ ) is asymptotically unbiased for _g_ ( _θ_ ) for any continuous function _g_
_a.s._

    - In the example of estimating 1/ _µ_ by _Tn_ = 1/ _X_ [¯], _Tn_ → 1/ _µ_ by the
SLLN and the continuous mapping. Hence _Tn_ is asymptotically
unbiased, although _ETn_ may not be well-defined.


LIN Zhenhua (NUS) Lecture 9 19 / 28


# Asymptotic Mean Squared Error (amse)

Like the bias, the variance and MSE of an estimator is not well defined if
its second moment does not exist









LIN Zhenhua (NUS) Lecture 9 20 / 28

LaTeX proof hint:
(empty)
-/
theorem continuous_mapping_theorem : True := by
  sorry

/-
ID: lecture_9_handout.theorem.013.slutsky_theorem
Title: Theorem 13
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.013.slutsky_theorem

LaTeX statement:
: MLE for the Exponential Mean

Let _X_ 1 _,...,Xn_ be i.i.d. drawn from the density _f_ ( _x_ ; _λ_ ) = _λ_ [−][1] _e_ [−] _[x]_ [/] _[λ]_ for
_x_ - 0 and _λ_ - 0

  - Note that _λ_ = E( _X_ 1) is the population mean and Var( _X_ 1) = _λ_ [2]

  - Estimate _λ_ by the sample mean



_λ_ ˆ = _X_ ¯ = [1]

_n_



_n_
∑ _Xi_
_i_ =1




- By CLT,
~~√~~
_n_



�→D _N_ (0 _,_ 1) _._
_λ_ [(] _[λ]_ [ˆ][ −] _[λ]_ [)]




- By Slutsky’s theorem,
~~√~~
_n_



( _λ_ [ˆ]  - _λ_ ) �→D _N_ (0 _,_ 1) _._
_λ_ ˆ




- Asymptotic (1 − _α_ ) confidence interval for _λ_ is

_X_ ¯ ± _z_ 1− _α_ /2 ~~√~~ _X_ ¯ _n_
_n_

LINhZhenhua _X_ ¯(NUS) l _θ_ b th Lecturel i9 i i l 28 / 28

LaTeX proof hint:
(empty)
-/
theorem slutsky_theorem : True := by
  sorry

end PipelineGenerated
