import Mathlib.MeasureTheory.Measure.MeasureSpace
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.MeasureTheory.Integral.Lebesgue.Basic
import Mathlib.MeasureTheory.Function.LpSpace.Basic
import Mathlib.Probability.IdentDistrib
import Mathlib.Probability.Independence.Basic

open MeasureTheory ProbabilityTheory Filter

/-! # Pipeline/Lecture9Handout

Pipeline-generated declarations for Pipeline.Lecture9Handout.
-/

namespace Statlean.Pipeline.Lecture9Handout

end Statlean.Pipeline.Lecture9Handout

section PipelineGenerated
/-! Declarations generated by the pipeline. -/

/-
ID: lecture_9_handout.theorem.003.theorem_3
Title: Theorem 3
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.003.theorem_3

LaTeX statement:
Let _X_ 1 _,X_ 2 _,..._, _Y_ be random variables, and { _an_ } is a sequence
of positive numbers with lim _n_ →∞ _an_ = ∞ satisfying


_D_
_an_ ( _Xn_             - _c_ ) → _Y,_
where _c_ ∈R. Let _g_ be a function from R to R.


(i) If _g_ is differentiable at _c_, then


_an_ [ _g_ ( _Xn_ ) − _g_ ( _c_ )] → _D_ _g_ ′( _c_ ) _Y_
where _g_ [′] ( _x_ ) is the derivatives of _g_ at _x_
(ii) Suppose that _g_ has continuous derivatives of order _m_ - 1 in a
neighborhood of _c_, s.t.
_g_ [(] _[j]_ [)] ( _c_ ) = 0 for all 1 ≤ _j_ ≤ _m_   - 1, and _g_ [(] _[m]_ [)] ( _c_ ) ≠ 0. Then


_D_ 1
_a_ _[m]_ _n_ [[] _[g]_ [ (] _[X][n]_ [) −] _[g]_ [(] _[c]_ [)]] → _[m]_

_m_ ! _[g]_ [(] _[m]_ [)][(] _[c]_ [)] _[Y]_


LIN Zhenhua (NUS) Lecture 9 7 / 28

LaTeX proof hint:
(empty)
-/
theorem theorem_003_theorem_3 : True := by
  sorry

/-
ID: lecture_9_handout.theorem.005.theorem_5
Title: Theorem 5
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.005.theorem_5

LaTeX statement:
s

Suppose _X_ 1 _,...,Xn_ IID with Var( _X_ 1) = 1, _X_ _n_ = _n_ [−][1] ∑ _[n]_ _i_ =1 _[X][i]_ [,] _[c]_ [ =][ E] _[X]_ [1][,]
_an_ = ~~[√]~~ _n_, and _Z_ ∼ _N_ (0 _,_ 1)

  - If _g_ ( _x_ ) = _x_ [2],

    - if _c_ ≠ 0 then ~~[√]~~ _n_ ( _X_ ~~2~~ _n_ [−] _[c]_ [2][)] → _D_ _N_ (0 _,_ 4 _c_ 2) since _g_ ′( _c_ ) = 2 _c_ ;

    - if _c_ = 0, then _g_ [′] ( _c_ ) = 0 but _g_ [′′] ( _c_ ) = 2 ≠ 0, so we have

( ~~[√]~~ _n_ ) [2] ( _X_ ~~2~~ _n_ [−] [0][)] → _D_ _Z_ 2 ∼ _χ_ 21

  - If _g_ ( _x_ ) = _x_ [−][1] and _c_ ≠ 0, then ~~[√]~~ _n_ ( _X_ ~~−~~ _n_ 1 [−] _[c]_ [−][1][)] → _D_ _N_ (0 _,_ 1/ _c_ 4), since
_g_ [′] ( _c_ ) = − _c_ [−][2] .


LIN Zhenhua (NUS) Lecture 9 9 / 28

LaTeX proof hint:
(empty)
-/
theorem theorem_005_theorem_5 : True := by
  sorry

/-
ID: lecture_9_handout.theorem.012.asymptotic_relative_efficiency
Title: Cont.
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.012.asymptotic_relative_efficiency

LaTeX statement:
The asymptotic relative efficiency of _T_ 1 _n_ w.r.t. _T_ 2 _n_ is


_eT_ 1 _n,T_ 2 _n_ ( _θ_ ) = _θ_ /( _e_ _[θ]_         - 1) < 1 _,_ ∀ _θ_         - 0


This shows that _T_ 2 _n_ is asymptotically more efficient than _T_ 1 _n_


LIN Zhenhua (NUS) Lecture 9 26 / 28


# Asymptotic Confidence Intervals

Let _θ_ [ˆ] _n_ be an estimator of a scalar parameter _θ_ 0 based on a sample of size
_n_ . If
~~√~~ _n_ ( _θ_ ˆ _n_       - _θ_ 0) �→D _N_ (0 _,V_ ) _,_


then for large _n_,
_θ_ ˆ _n_ ≈ _D_ _N_ ( _θ_ 0 _,_ _[V]_

_n_ [)] _[.]_













LIN Zhenhua (NUS) Lecture 9 27 / 28

LaTeX proof hint:
(empty)

Lean sketch (reference, not compiled):
def asymptotic_relative_efficiency
    {Ω : Type*} [MeasurableSpace Ω] (P : ℕ → Measure Ω)
    (T₁ T₂ : ℕ → Ω → ℝ) (ϑ : ℝ) (a : ℕ → ℝ)
    (V₁ V₂ : ℝ) : ℝ :=
    V₂ / V₁
-/
theorem asymptotic_relative_efficiency : True := by
  sorry

end PipelineGenerated
