import Statlean.Basic

/-! # LimitTheorems/CLT

Pipeline-generated declarations for LimitTheorems.CLT.
-/

namespace Statlean.LimitTheorems.CLT

end Statlean.LimitTheorems.CLT

section PipelineGenerated
/-! Declarations generated by the pipeline. -/

/-
ID: lecture_9_handout.theorem.001.t_distribution_clt_example
Title: Theorem 1
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.001.t_distribution_clt_example

LaTeX statement:
- Let _X_ 1 _,...,Xn_ be independently and identically distributed random
variables with mean 0 and variance 1.

 - The ch.f. of _X_ 1 satisfies



_ϕX_ 1( _t_ ) = _ϕX_ 1(0) − [1]




[1] as ∣ _t_ ∣→ 0.

2 _[t]_ [2][ +] _[ o]_ [(∣] _[t]_ [∣][2][)] _[,]_




- Let _Tn_ = _X_ 1 + ⋯+ _Xn,n_ = 1 _,_ 2 _,..._ The ch.f. of _Tn_ / ~~[√]~~ _n_ is



_ϕTn_ / ~~[√]~~ _n_ ( _t_ ) = [1 − _[t]_ [2]




_[t]_ [2]

2 _n_ [+] _[ o]_ [(] _[t]_ _n_ [2]



_n_ [)]]



_n_
_,_ ∀ _t_ ∈R




- _ϕTn_ / ~~[√]~~ _n_ ( _t_ ) → _e_ [−] _[t]_ [2][/][2], the ch.f. of _N_ (0 _,_ 1) _._

- Hence _Tn_ / ~~[√]~~ _n_ → _d N_ (0 _,_ 1)


LIN Zhenhua (NUS) Lecture 9 2 / 28


If _X_ has a p.d.f. _f_ and _Xn_ has a p.d.f. _fn_, we have another way to check

whether _Xn_ →D _X_






 - Let _gn_ ( _x_ ) = [ _f_ ( _x_ ) − _fn_ ( _x_ )] _I_ { _f_ ≥ _fn_ }( _x_ ) _,n_ = 1 _,_ 2 _,..._ Then


∫ [∣] _[f]_ _n_ [(] _[x]_ [) −] _[f]_ [(] _[x]_ [)∣] _[dν]_ [=][ 2] ∫ _[g]_ _n_ [(] _[x]_ [)] _[dν]_


 - Since 0 ≤ _gn_ ( _x_ ) ≤ _f_ ( _x_ ) for all _x_ and _gn_ → 0 a.e. _ν,_ the result follows
from DCT.

 - Let _Fn_ and _F_ be the c.d.f. of _fn_ and _f_ . For any _x_ ∈ R _[k]_, let
_A_ = { _y_ ∈ R _[k]_ ∶ _yi_ ≤ _xi,i_ = 1 _,...,k_
...

LaTeX proof hint:
(empty)
-/
theorem t_distribution_clt_example : True := by
  sorry

/-
ID: lecture_9_handout.theorem.004.central_limit_theorem
Title: Theorem 4
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.004.central_limit_theorem

LaTeX statement:
Suppose _X_ 1 _,...,Xn_ are i.i.d. sample from _Pλ_ with p.d.f.


_fX_ ( _x_ ) = _λe_ [−] _[λx]_ _,_ _x_ ∈[0 _,_ ∞) _,_


where the parameter _λ_ - 0 is called the rate

  - _µ_ = E _X_ = 1/ _λ_, or _λ_ = _µ_ [−][1]

  - Var( _X_ ) = _µ_ [2]

  - Let _µ_ ˆ _n_ = _X_ [¯] _n_ and _λ_ [ˆ] _n_ = _µ_ ˆ [−] _n_ [1] [=][ 1][/] _[X]_ [ ¯] _[n]_

  - CLT says that ~~[√]~~ _n_ ( _µ_ ˆ _n_  - _µ_ ) → _D_ _Z_ ∼ _N_ (0 _,µ_ 2)

  - Apply _δ_ -method with _c_ = _µ_, _g_ ( _µ_ ) = _µ_ [−][1] = _λ_

  - Since _g_ [′] ( _µ_ ) = − _µ_ [−][2] = − _λ_ [2], we have

~~√~~ _n_ ( _λ_ ˆ _n_       - _λ_ ) →− _D_ _λ_ 2 _Z_ ∼ _N_ (0 _,λ_ 2)


LIN Zhenhua (NUS) Lecture 9 8 / 28

LaTeX proof hint:
(empty)
-/
theorem central_limit_theorem : True := by
  sorry

/-
ID: lecture_9_handout.theorem.006.lindeberg_feller_clt
Title: Theorem 6
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.006.lindeberg_feller_clt

LaTeX statement:
s


  - Condition (1) controls the tails of _Xnj_, and is called _Lindeberg’s_
_condition_ .

  - Condition (1) is implied by either of the following

    - Lyapunov condition:



1
_σn_ [2][+] _[δ]_



_kn_
∑ E∣ _Xnj_ - E _Xnj_ ∣ [2][+] _[δ]_ → 0 for some _δ_ - 0.
_j_ =1




  - Uniform boundedness: if ∣ _Xnj_ ∣≤ _M_ for all _n_ and _j_ and
_σn_ [2] [= ∑] _j_ _[k]_ = _[n]_ 1 [Var][(] _[X][nj]_ [) →∞][.]

- In general, Condition (1) is NOT necessary for the convergence result.

- But if we assume the _Feller’s_ _condition_ :


Var( _Xnj_ )
lim = 0 _,_
_n_ →∞ [max] _j_ ≤ _kn_ _σn_ [2]


then Condition (1) is not only sufficient but also necessary


LIN Zhenhua (NUS) Lecture 9 15 / 28

LaTeX proof hint:
(empty)
-/
theorem lindeberg_feller_clt : True := by
  sorry

/-
ID: lecture_9_handout.theorem.010.central_limit_theorem
Title: Theorem 10
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.010.central_limit_theorem

LaTeX statement:
Let _T_ 1 _n_ = _n_ [1] [∑] _j_ _[n]_ =1 _[I]_ { _Xj_ =0}

  - _T_ 1 _n_ is unbiased and has mse _T_ 1 _n_ ( _θ_ ) = _e_ [−] _[θ]_ (1 − _e_ [−] _[θ]_ )/ _n_

  - By CLT, ~~√~~ _n_ ( _T_ 1 _n_  - _τ_ ) →D _N_ (0 _,e_  - _θ_ (1 − _e_  - _θ_ ))

  - So amse _T_ 1 _n_ ( _θ_ ) = mse _T_ 1 _n_ ( _θ_ )


LIN Zhenhua (NUS) Lecture 9 24 / 28

LaTeX proof hint:
(empty)
-/
theorem central_limit_theorem_v2 : True := by
  sorry

/-
ID: lecture_9_handout.theorem.011.central_limit_theorem
Title: Cont.
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.011.central_limit_theorem

LaTeX statement:
Next, consider _T_ 2 _n_ = _e_ [−] _X_ [¯]

  - By CLT, ~~[√]~~ _n_ ( _X_ [¯]  - _θ_ ) →D _N_ (0 _,θ_ )

  - By _δ_ -method, we have ~~[√]~~ _n_ ( _T_ 2 _n_  - _τ_ ) →D _N_ (0 _,e_ −2 _θθ_ )

  - So _T_ 2 _n_ is asymptotic unbiased and amse _T_ 2 _n_ ( _θ_ ) = _e_ [−][2] _[θ]_ _θ_ / _n_

  - Note that _ET_ 2 _n_ = _e_ _[nθ]_ [(] _[e]_ [−][1][/] _[n]_ [−][1][)] and _nbT_ 2 _n_ ( _θ_ ) → _θe_ [−] _[θ]_ /2. The exact bias
of _T_ 2 _n_ is not _o_ (1/ _n_ )


LIN Zhenhua (NUS) Lecture 9 25 / 28

LaTeX proof hint:
(empty)
-/
theorem central_limit_theorem_v3 : True := by
  sorry

end PipelineGenerated
