import Statlean.Statistic.Basic
import Mathlib.Analysis.Calculus.Deriv.Basic

/-! # Information/Basic

Fisher information and score function for parametric statistical models.

The Fisher information `I(θ) = E[(∂/∂θ log f_θ(X))²]` measures
the amount of information about θ contained in an observation.
-/

open MeasureTheory

variable {Ω : Type*} [MeasurableSpace Ω]

/-- The score function ∂/∂θ log f_θ(x), defined via the derivative of the
log-density. Here `logDensity θ ω` represents `log f_θ(ω)`. -/
noncomputable def scoreFunction
    (logDensity : ℝ → Ω → ℝ) (θ : ℝ) (ω : Ω) : ℝ :=
  deriv (fun θ' => logDensity θ' ω) θ

/-- Fisher information: `I(θ) = E_θ[(∂/∂θ log f_θ(X))²]`. -/
noncomputable def fisherInformation
    (P : ParametricFamily ℝ Ω) (logDensity : ℝ → Ω → ℝ) (θ : ℝ) : ℝ :=
  ∫ ω, (scoreFunction logDensity θ ω) ^ 2 ∂(P.measure θ)

section PipelineGenerated
/-! Declarations generated by the pipeline. -/

/-
ID: lecture_9_handout.theorem.009.fisher_information
Title: Theorem 9
Kind: theorem
PIPELINE_ID: lecture_9_handout.theorem.009.fisher_information

LaTeX statement:
s


  - It holds that “amse= asym. bias [2] + asym. variance” if they are all
well defined

  - In the definition, the amse and asymptotic variance are the same if
and only if _EY_ = 0

  - In the definition, one can show that


_EY_ [2] ≤ liminf _n_ →∞ _[E]_ [ [] _[a]_ _n_ [2] [(] _[T][n]_ [−] _[ϑ]_ [)][2][]]


    - Proof is left for exercise: use Skorohod’s theorem and Fatou’s lemma

    - The equality holds if and only if { _a_ [2] _n_ [(] _[T][n]_ [−] _[ϑ]_ [)][2][}] [is] [uniformly] [integrable.]

    - In other words, the amse is no greater than the exact mse and they are
equal under a certain condition.


LIN Zhenhua (NUS) Lecture 9 21 / 28


# Asymptotic Relative Efficiency

Let _Tn_ and _Tn_ [′] [be] [two] [estimators] [of] _[ϑ]_

  - The **asymptotic** **relative** **efficiency** **of** _Tn_ [′] **[w.r.t.]** _[T][n]_ [is] [defined] [to] [be]


_eTn_ ′ _,Tn_ ( _P_ ) = amse _Tn_ ( _P_ )/ amse _Tn_ ′ ( _P_ )


  - _Tn_ is said to be **asymptotically** **more** **efficient** **than** _Tn_ [′] [if] [and] [only] [if]


limsup _eTn_ ′ _,Tn_ ( _P_ ) ≤ 1
_n_


for any _P_ and < 1 for some _P_

  - Historically, the “efficiency” of an estimator _T_ of _θ_ refers to
1/[ _I_ ( _θ_ )
...

LaTeX proof hint:
(empty)

Lean sketch (reference, not compiled):
noncomputable def fisherInformation
    {Ω : Type*} [MeasurableSpace Ω]
    (P : ℝ → Measure Ω) (ν : Measure Ω) [∀ θ, (P θ).AbsolutelyContinuous ν]
    (θ : ℝ) : ℝ :=
    ∫ ω, (deriv (fun θ' => Real.log ((P θ').rnDeriv ν ω).toReal) θ) ^ 2 ∂(P θ)
-/
theorem fisher_information : True := by
  sorry

end PipelineGenerated
