import Mathlib

open MeasureTheory ProbabilityTheory MeasurableSpace

/-! # Causal Inference on Distribution Functions

Formalization of the potential outcomes framework from:
  Lin, Kong, Wang (2022) "Causal Inference on Distribution Functions"

## Main definitions
- `CausalModel`: a potential outcomes model with binary treatment, covariates, and outcomes
- `CausalModel.Ignorability`: Assumption 1 — conditional independence of treatment and
  potential outcomes given covariates (A ⊥⊥ Y(a) | X)
- `CausalModel.Positivity`: Assumption 2 — propensity score bounded away from 0 and 1
- `CausalModel.propensityScore`: π(ω) = E[1_{A=1} | σ(X)](ω)
- `CausalModel.observedOutcome`: SUTVA-consistent observed outcome Y = Y(A)

## References
- Lin, Kong, Wang. "Causal Inference on Distribution Functions."
  arXiv:2101.01599v3, 2022.
-/

variable {d : ℕ}

/-- A potential outcomes causal model with binary treatment.
  - `Ω` is the sample space
  - `S` is the outcome space (may be non-linear, e.g. Wasserstein space)
  - `d` is the covariate dimension
  - `A` is the binary treatment indicator
  - `X` is the covariate vector in ℝ^d
  - `Y₁, Y₀` are the potential outcomes under treatment and control -/
structure CausalModel (Ω : Type*) (S : Type*) (d : ℕ)
    [MeasurableSpace Ω] [StandardBorelSpace Ω]
    [MeasurableSpace S] where
  /-- The probability measure on the sample space -/
  μ : Measure Ω
  /-- Treatment indicator (true = treated) -/
  A : Ω → Bool
  /-- Baseline covariates -/
  X : Ω → EuclideanSpace ℝ (Fin d)
  /-- Potential outcome under treatment (a = 1) -/
  Y₁ : Ω → S
  /-- Potential outcome under control (a = 0) -/
  Y₀ : Ω → S
  /-- Treatment is measurable -/
  hA : Measurable A
  /-- Covariates are measurable -/
  hX : Measurable X
  /-- Potential outcomes are measurable -/
  hY₁ : Measurable Y₁
  hY₀ : Measurable Y₀
  /-- Probability measure -/
  isProbability : IsProbabilityMeasure μ

namespace CausalModel

variable {Ω S : Type*} [MeasurableSpace Ω] [StandardBorelSpace Ω]
  [MeasurableSpace S] (M : CausalModel Ω S d)

/-- The σ-algebra generated by the covariates X. -/
def sigmaX : MeasurableSpace Ω :=
  MeasurableSpace.comap M.X inferInstance

/-- The covariate σ-algebra is a sub-σ-algebra of the ambient σ-algebra. -/
theorem sigmaX_le : M.sigmaX ≤ ‹MeasurableSpace Ω› :=
  M.hX.comap_le

/-! ## Assumption 1: Ignorability -/

/-- **Assumption 1 (Ignorability)**: A ⊥⊥ Y(a) | X, for a = 0, 1.

The treatment assignment is conditionally independent of each potential outcome
given the baseline covariates. This is the key unconfoundedness assumption
for causal identification. -/
def Ignorability : Prop :=
  haveI := M.isProbability
  CondIndepFun M.sigmaX M.sigmaX_le M.A M.Y₁ M.μ ∧
  CondIndepFun M.sigmaX M.sigmaX_le M.A M.Y₀ M.μ

/-! ## Propensity score and Assumption 2: Positivity -/

/-- The propensity score π(ω) = E[1_{A=1} | σ(X)](ω), defined as the conditional
expectation of the treatment indicator given the covariate σ-algebra.

Lin et al. (2022), Section 2.1: π(X) := P(A = 1 | X). -/
noncomputable def propensityScore : Ω → ℝ :=
  haveI := M.isProbability
  condExp M.sigmaX M.μ (fun ω => if M.A ω then (1 : ℝ) else 0)

/-- **Assumption 2 (Positivity)**: The propensity score is bounded away from 0 and 1.

There exists ε > 0 such that ε < π(X) < 1 - ε almost everywhere.
This ensures that both treatment groups have positive probability
conditional on any covariate value. -/
def Positivity : Prop :=
  haveI := M.isProbability
  ∃ ε : ℝ, 0 < ε ∧ ∀ᵐ ω ∂M.μ, ε < M.propensityScore ω ∧ M.propensityScore ω < 1 - ε

/-- Under Positivity, the propensity score is strictly positive a.e. -/
theorem Positivity.propensityScore_pos (h : M.Positivity) :
    ∀ᵐ ω ∂M.μ, 0 < M.propensityScore ω := by
  obtain ⟨ε, hε, hae⟩ := h
  filter_upwards [hae] with ω ⟨hlb, _⟩
  linarith

/-- Under Positivity, the propensity score is strictly less than 1 a.e. -/
theorem Positivity.propensityScore_lt_one (h : M.Positivity) :
    ∀ᵐ ω ∂M.μ, M.propensityScore ω < 1 := by
  obtain ⟨ε, hε, hae⟩ := h
  filter_upwards [hae] with ω ⟨_, hub⟩
  linarith

/-! ## SUTVA and observed outcome -/

/-- The observed outcome Y = Y(A): under SUTVA, the observed outcome is the
potential outcome corresponding to the assigned treatment level. -/
def observedOutcome : Ω → S :=
  fun ω => if M.A ω then M.Y₁ ω else M.Y₀ ω

/-- SUTVA is built into the model: the observed outcome equals the potential
outcome for the assigned treatment. -/
theorem sutva (ω : Ω) :
    M.observedOutcome ω = if M.A ω then M.Y₁ ω else M.Y₀ ω := rfl

/-! ## Symmetry of ignorability -/

/-- Ignorability is symmetric in the treatment indicator: if A ⊥⊥ Y(a) | X then
Y(a) ⊥⊥ A | X. -/
theorem Ignorability.symm (h : M.Ignorability) :
    haveI := M.isProbability
    CondIndepFun M.sigmaX M.sigmaX_le M.Y₁ M.A M.μ ∧
    CondIndepFun M.sigmaX M.sigmaX_le M.Y₀ M.A M.μ := by
  haveI := M.isProbability
  exact ⟨h.1.symm, h.2.symm⟩

end CausalModel
